# Generated by Django 2.1.3 on 2018-12-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181203_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followings',
            new_name='following',
        ),
    ]
