(function(g){var window=this;var TY=function(a){a.g||(a.g=new g.mp,g.H(a,a.g));return a.g},UY=function(a){a.M("cardstatechange",a.jd()&&a.ne()?1:0)},VY=function(a){var b=g.zi(a);
a=g.Gi(a);return new g.bi(b.x,b.y,a.width,a.height)},WY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},XY=function(a){return"none"!=a.style.display},Tla=function(a){var b=g.ti(a,"fontSize");
var c=(c=b.match(Qla))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.ne){if(String(c)in Rla)return g.Ii(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Sla)return a=a.parentNode,c=g.ti(a,"fontSize"),g.Ii(a,b==c?"1em":b,"left","pixelLeft")}c=g.te("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Ae(c);return b},Ula=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ll&&a.dataset){if(g.vc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Ic("pollChoiceIndex"))},$Y=function(a){a=g.Sa(a);
delete YY[a];g.jc(YY)&&ZY&&ZY.stop()},aZ=function(){ZY||(ZY=new g.L(function(){Vla()},20));
var a=ZY;a.isActive()||a.start()},Vla=function(){var a=(0,g.C)();
g.Xb(YY,function(b){bZ(b,a)});
g.jc(YY)||aZ()},cZ=function(a,b){g.$f.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},dZ=function(a,b,c,d){g.Lo.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},bZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;eZ(a,a.progress);1==a.progress?(a.g=0,$Y(a),a.Pc(),a.l()):1==a.g&&a.Mq()},eZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},fZ=function(a,b,c,d,e){dZ.call(this,b,c,d,e);
this.element=a},gZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
fZ.apply(this,arguments)},Wla=function(a){return Math.pow(a,3)},Xla=function(a){return 3*a*a-2*a*a*a},hZ=function(a){g.F.call(this);
this.i=a||window;this.g=[]},Yla=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.ps(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},iZ=function(a,b){(0,g.A)(b,function(b){g.ct("visualElementShown",{csn:a,
ve:g.lt(b),eventType:4},g.ht,void 0,void 0)})},jZ=function(a,b){(0,g.A)(b,function(b){g.ct("visualElementHidden",{csn:a,
ve:g.lt(b),eventType:8},g.ht,void 0,void 0)})},kZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Qc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={DC:a.impression,click:a.click,close:a.close,fL:a.teaser_impression,Lr:a.teaser_click};b=b.tracking_params||{};this.A=g.kt(b.card);this.D=g.kt(b.teaser);this.u=g.kt(b.icon)},lZ=function(a,b){g.Cg.call(this);
this.gj=a;this.To=b;this[g.bg]=!1},qZ=function(a,b,c,d){lZ.call(this,a,b);
a=this.To;b=this.ha();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.t(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Zla(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.To;a=this.ha();if(d instanceof mZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof nZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=oZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=oZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=oZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=pZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},rZ=function(){},sZ=function(a,b){lZ.call(this,a,b)},tZ=function(){this.Ua=[];
this.ya=[];this.Fd=[]},uZ=function(a,b,c,d){var e=a.ld[0]-b*Math.cos(g.Vd(d))+b*Math.cos(g.Vd(d+90)),f=a.ld[1]-c*Math.sin(g.Vd(d))+c*Math.sin(g.Vd(d+90));
a.Ua.push(3);a.ya.push(1);a.Fd.push(b,c,d,90,e,f);a.dk=!1;a.ld=[e,f]},ama=function(a,b){for(var c=a.Fd,d=0,e=0,f=a.Ua.length;e<f;e++){var k=a.Ua[e],l=$la[k]*a.ya[e];
b(k,c.slice(d,d+l));d+=l}},vZ=function(a,b,c,d){qZ.call(this,a,b,c,d)},wZ=function(a,b){this.g=a;
this.i=b},xZ=function(a,b,c,d,e){g.Wo.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.N=d||null},Zla=function(a){var b=a.Wi();
return b?b.width/(a.l?new g.Zd(a.l,a.N):a.Wi()).width:0},nZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Fa(k)?k:null;this.o=g.Fa(l)?l:null},mZ=function(a,b){this.F=a;
this.H=null==b?1:b},yZ=function(a,b){lZ.call(this,a,b)},zZ=function(a,b,c,d){qZ.call(this,a,b,c,d)},AZ=function(a,b,c,d,e){xZ.call(this,a,b,c,d,e);
this.g={};this.R=g.pe&&!g.Tc(526);this.K=new g.Pn(this)},oZ=function(a,b,c){a=a.O.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},BZ=function(a,b,c,d){b=oZ(a,"path",{d:bma(b)});
c=new zZ(b,a,c,d);a.o.ha().appendChild(c.ha())},bma=function(a){var b=[];
ama(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},pZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+cma++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},dma=function(){CZ||(CZ=new g.sh(400),CZ.start());
return CZ},DZ=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.D)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.D)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.kt(a.trackingParams);var k=(0,g.D)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.ku=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.D)(x.loggingUrls||[],c);l.Ak=g.ec(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.D)(k.impressionUrls||[],c);l.BC=(0,g.D)(k.hovercardShowUrls||[],c);l.Qc={itct:k.trackingParams};l.visualElement=g.kt(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.yl=!1,l.en=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.yl=!1,l.en=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.ec(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.yl=!1;l.en="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var B=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var G=d(m.subscriberCountText)}else E=d(m.subscriberCountText),G=d(m.subscriberCountWithSubscribeText);
var S=null;if(k.signinEndpoint&&(S=g.ec(k,"signinEndpoint","webNavigationEndpointData","url"),!S)){k=void 0;break a}if(x&&(B||S)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:E,unsubscribeText:B,unsubscribeCount:G,enabled:m.enabled,signinUrl:S,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.ec(x,"urlEndpoint","url"),l.yl=!0,l.en="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.Ce)(k,function(a){return!!a});
return f},EZ=function(a){g.rK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.N=[];a=g.W(a);this.K=g.cz(a)||g.dz(a);this.uz=!0;this.D=0;this.F=new g.Bo;this.u=new g.us(this);g.H(this,this.u);this.u.J(this.player,g.WD("creatorendscreen"),this.zD);this.u.J(this.player,"crx_creatorendscreen",this.AD);this.u.J(this.player,"resize",this.nb);this.u.J(window,"focus",this.lK);this.load();var b=g.ve("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Wf(this,function(){g.Ae(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},FZ=function(a){return a.player.getVideoData().Yb?"current":a.K?"new":"current"},GZ=function(a){return"creator-endscreen-editor"===a},HZ=function(a,b){g.bK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.N.length&&(a.N.forEach(function(a){a.dispose()}),a.N.length=0);
a.D=0;if((a.i=b)&&b.elements){ema(a);c=[];var d=new g.TD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.W(a.player).g||(a.l=new g.T({B:"div",G:"ytp-ce-shadow"}),g.fK(a.player,a.l.element,4),a.A=new g.DP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=fma(a,e);a.g[e.id]=f;a.C[e.id]=e;g.fK(a.player,f.element,4);var k=new g.TD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);gma(a,f,e)}g.ZJ(a.player,
c);a.nb()}},ema=function(a){var b=g.Et(),c=g.Ft();
c&&b&&g.mt(c,b,[a.i.visualElement])},fma=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:IZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Co(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:IZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Co(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",I:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",I:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Co(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",I:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:IZ(b)}]};c=new g.T(c);var d=g.fe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.W(a.player).g){var e=null;var f=b.Qc.itct}else e="endscreen",f=null;e=new g.pV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",
I:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Co(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:IZ(b)},{B:"div",G:"ytp-ce-expanding-icon",L:JZ(b.iconUrl)}]},c=new g.T(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},IZ=function(a){if(a.ku)var b=a.ku.thumbnails;
return JZ(b?b[b.length-1].url:null)},JZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},gma=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.y)(a.Zp,a,b,c));b.ca("mouseleave",(0,g.y)(a.Tq,a,b,c));g.W(a.player).g||b.ca("click",(0,g.y)(function(a){g.J(a.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.y)(a.Dx,a,c));b.ca("keypress",(0,g.y)(a.Dx,a,c));b.ca("focus",(0,g.y)(function(a,b){this.Zp(a,b)},a,b,c));
b.ca("blur",(0,g.y)(function(a,b){this.Tq(a,b)},a,b,c));
b.ca("touchstart",(0,g.y)(a.Zp,a,b,c));var f=g.he("ytp-ce-expanding-overlay-hider",b.element);f&&b.J(f,"touchstart",function(a){g.ls(a);g.Io(b.element,"ytp-ce-element-hover");g.Io(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.y)(function(a,b){this.uz=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.y)(function(a,b,c){this.D+=c;0<this.D?(g.J(a.element,"ytp-ce-force-expand"),KZ(this,b.id,!0)):(g.Io(a.element,"ytp-ce-force-expand"),g.Io(a.element,"ytp-ce-element-hover"),KZ(this,b.id,!1))},a,b,c);
a=(0,g.y)(function(a,b){b&&(a.ca("blur",function(){XY(b)&&this.uz&&b.focus()}),a.J(b,"focus",d),a.J(b,"blur",e))},a,b);
a(g.he("ytp-sb-subscribe",b.element));a(g.he("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},KZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},LZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||GZ(g.W(a.player).playerStyle))c&&c();else{b=hma(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Cr(b[a],d)}},MZ=function(a,b,c){LZ(a,b.clickUrls,c);
(a=g.Ft())&&b.yl&&g.ot(a,b.visualElement)},hma=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(jma(b[e],c));return d},jma=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},NZ=function(a){return g.Ma(a)&&a.length?a[0]:a},OZ=function(a){var b=/.+/;
return g.t(a)&&null!=b&&null!=a&&a.match(b)?a:""},PZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},QZ=function(a){return g.t(a)?a:""},RZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},SZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},TZ=function(a,b){return g.t(a)?parseFloat(a):b},UZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Sd(a,b,c);if(a>=b&&a<=c)return a}return e},kma=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},VZ=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},lma=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.Zh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},mma=function(a){function b(a){return(0,g.Ce)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},nma=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},WZ=function(a){if(!a)return null;
var b=g.sd(QZ(a.value));b=g.pd(b);if(!b)return null;var c=RZ(a.target,oma,"current");return null==c?null:new nma(b,c,SZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},XZ=function(a){return a.value?a.value:null},pma=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},sma=function(a){if(!a)return null;
var b=RZ(a.type,qma),c=RZ(a.trigger,rma),d=NZ(a.url);d=WZ(d?d:null);NZ(a.subscribeData);return b?new pma(b,c,d):null},YZ=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},ZZ=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},$Z=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.ii=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},a_=function(a,b){if(!a)return null;
var c=TZ(a.x,0),d=TZ(a.y,0),e=TZ(a.w,0),f=TZ(a.h,0),k=kma(a.t),l=TZ(a.d,0),m=TZ(a.px,0),n=TZ(a.py,0),p=TZ(a.scaleSlope,1),u=TZ(a.scaleSlopeX,p);p=TZ(a.scaleSlopeY,p);var x=RZ(a.scaleDimension,tma,"xy");return b(c,d,e,f,k,l,m,n,u,p,x)},d_=function(a,b){var c=b_(b,c_(a,new g.bi(a.x,a.y,a.ii,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Sd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Sd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},c_=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=YZ(c,a.o,f);
a=ZZ(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.bi(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},e_=function(a){return a?a_(a,function(a,c,d,e,f,k,l,m,n,p,u){return new $Z(a,c,d,e,f,k,l,m,n,p,u)}):null},f_=function(a,b){this.g=a;
this.i=b||null},b_=function(a,b){var c=a.i?d_(a.i,new f_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Wd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},g_=function(a,b,c,d,e,f,k,l,m,n,p,u,x){$Z.call(this,a,b,c,d,e,l,m,n,p,u,x);
this.D=f;this.F=k},uma=function(a){if(!a)return null;
var b=TZ(a.sx,0),c=TZ(a.sy,0);return a_(a,function(a,e,f,k,l,m,n,p,u,x,B){return new g_(a,e,f,k,l,b,c,m,n,p,u,x,B)})},vma=function(a,b,c,d,e,f,k,l,m,n,p,u,x,B){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=u;this.cornerRadius=x;this.u=B},h_=function(a){if(!a)return null;
var b=PZ(a.fgColor,"#1A1A1A"),c=PZ(a.bgColor,"#FFF"),d=PZ(a.borderColor,"#000"),e=UZ(a.borderWidth,0,5,!1,0),f=UZ(a.bgAlpha,0,1,!1,.8),k=PZ(a.highlightFontColor,"#F2F2F2"),l=UZ(a.highlightWidth,0,5,!1,3),m=QZ(a.textAlign),n=UZ(a.textSize,3.3,30.1,!0,3.6107),p=QZ(a.fontWeight),u=lma(a.padding),x=mma(a.effects),B=UZ(a.cornerRadius,0,10,!0,0);a=NZ(a.gradient);if(a=a?a:null){var E=UZ(a.x1,0,100,!0,0),G=UZ(a.y1,0,100,!0,0),S=UZ(a.x2,0,100,!0,100),V=UZ(a.y2,0,100,!0,100),ra=PZ(a.color1,"#FFF"),vb=PZ(a.color2,
"#000");a=new wma(E,G,S,V,ra,vb,UZ(a.opacity1,0,100,!0,100),UZ(a.opacity2,0,100,!0,0))}else a=null;return new vma(b,c,d,e,f,k,l,m,n,p,u,x,B,a)},wma=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},xma=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},zma=function(a){if(!a)return null;
var b=RZ(a.type,yma,"rect"),c=VZ(a.rectRegion,e_),d=VZ(a.anchoredRegion,uma);a=VZ(a.shapelessRegion,e_);return new xma(b,c,d,a)},i_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Ama=function(a,b){this.i=a;
this.g=b},Bma=function(a,b){this.state=a;
this.ref=b},j_=function(a){if(!a)return null;
var b=RZ(a.state,Cma);a=OZ(a.ref);return b?new Bma(b,a):null},Dma=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Ema=function(a){if(!a)return null;
var b=VZ(a.condition,j_),c=VZ(a.notCondition,j_),d=SZ(a.show_delay,!1);a=SZ(a.hide_delay,!1);return b||c?new Dma(b,c,d,a):null},Fma=function(a,b,c){(0,g.A)(a.g,g.Va(b,!1),c);
(0,g.A)(a.l,g.Va(b,!0),c)},k_=function(a,b,c,d,e,f,k,l,m,n,p,u,x,B){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.C=l||[];this.i=m;this.A=n;this.u=p;this.data=u;this.g=x;this.itct=B},Ima=function(a){if(!a)return null;
var b=OZ(a.id),c=OZ(a.author),d=RZ(a.type,Gma),e=RZ(a.style,l_),f=QZ(NZ(a.TEXT)),k=QZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=NZ(a.segment);var m=l?l:null;m?(OZ(m.timeRelative),l=OZ(m.spaceRelative),l=(m=VZ(m.movingRegion,zma))?new Ama(l,m):null):l=null;m=VZ(a.action,sma);var n=VZ(a.trigger,Ema),p=NZ(a.appearance);(p=h_(p?p:null))||(p=h_({}));var u=RZ(a.coordinate_system,Hma,"video_relative"),x=SZ(a.closeable,!0),B=QZ(a.log_data);a=QZ(a.itct);return b&&d?new k_(b,c,d,e,f,l,m,n,p,u,x,k,B,a):null},
n_=function(a){return m_(a,function(a){return"click"==a.trigger})},m_=function(a,b){return(0,g.nk)(a.l,b,void 0)},Jma=function(a,b,c){(0,g.A)(a.l,b,c)},Kma=function(a,b){return g.bb(a.l,b,void 0)},o_=function(a,b,c){(0,g.A)(a.C,b,c)},Lma=function(a,b){(0,g.D)(a.C,b,void 0)},q_=function(a){return(a=p_(a))?i_(a):null},p_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},r_=function(a,b){var c=q_(a);
return c&&b?ZZ(b,c.i,c.g?c.g:"xy"):1},t_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Fma(b,function(a,b){var c=s_(b.state,b.ref);this.i.subscribe(c,(0,g.y)(this.o,this,c,a));this.g[c]=a},this)},s_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},u_=function(){this.g=!1;
this.u=this.i=null},v_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new AZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Yo(),a.u=g.te("DIV"),a.u.appendChild(a.i.ha()));
return a.i},w_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Xb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},x_=function(a,b){var c=g.Vo(g.Uo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Mma=function(a,b){var c=x_(a,w_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=x_(a,w_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},w_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=x_(a,w_("feComposite",{"in":c,in2:b,operator:"in"}));return x_(a,w_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Nma=function(a,b){var c=x_(a,w_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=x_(a,w_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=x_(a,w_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=x_(a,w_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=x_(a,w_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=x_(a,w_("feComposite",{operator:"out","in":c,in2:d}));return x_(a,w_("feComposite",{operator:"over","in":b,in2:c}))},Oma=function(a,b){return b},Pma=function(a){var b=
w_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(a){a:{switch(a){case "bevel":a=Mma;break a;case "dropshadow":a=Nma;break a}a=Oma}c=a(b,c)});
return b},Qma=function(a){a=(0,g.Ce)(a,function(a){return a in y_});
g.yb(a,function(a,c){return y_[a]-y_[c]});
return a},Rma=function(a){return g.bb(a,function(a){return"dropshadow"==a})?new g.Zh(0,7,7,0):new g.Zh(0,0,0,0)},z_=function(a,b,c){var d=new tZ;
d.moveTo(a.left+b+c,a.top+c);d.Xb(a.left+a.width-b-c,a.top+c);uZ(d,b,b,-90);d.Xb(a.left+a.width-c,a.top+a.height-b-c);uZ(d,b,b,0);d.Xb(a.left+b+c,a.top+a.height-c);uZ(d,b,b,90);d.Xb(a.left+c,a.top+b+c);uZ(d,b,b,180);d.close();return d},A_=function(a,b,c,d){var e=a.u;
e?a=new nZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new mZ(a.bgColor,d?Math.max(b,.9):b));return a},B_=function(a,b){var c=g.ci(a),d=Rma(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.bi(c.left,c.top,c.right-c.left,c.bottom-c.top)},C_=function(a,b,c){if(c.length&&(b=g.fe(document,"g",void 0,b),b.length)){var d=Qma(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Pma(d),a=0<d.childNodes.length?pZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},D_=function(){u_.call(this);
this.o=0},Sma=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},E_=function(a){u_.apply(this,arguments)},F_=function(a){u_.apply(this,arguments)},G_=function(a){D_.apply(this,arguments)},H_=function(a,b,c,d,e){g.F.call(this);
this.g=a;this.P=b;this.A=c;this.ga=d;this.W=e;this.F=!1;this.aa=new hZ(this);g.H(this,this.aa);this.O=this.u=this.C=this.K=this.i=null;this.Z=!1;this.X=this.H=this.N=null;this.lm=new g.em(this.bC,100,this);g.H(this,this.lm);this.D=new g.L(this.rv,500,this);g.H(this,this.D);this.R=this.l=this.o=null},Tma=function(a,b){var c=(0,g.y)(function(a,c,f){c=f?I_(this,c,(0,g.y)(f,this)):I_(this,c);
this.aa.ca(b,a,c)},a);
c("mouseover","G",a.ow);c("mouseout","F",a.eg);c("click","D");c("touchend","D")},Uma=function(a){if(a.g.u){if(m_(a.g,function(a){return"close"==a.type}))var b=a.i;
else a.o=g.te("DIV","annotation-close-button"),g.Hi(a.o,!1),g.pq(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(a){a.stopPropagation()};
a.aa.ca(b,"click",I_(a,"E",c));a.aa.ca(b,"touchend",I_(a,"E",c))}},I_=function(a,b,c){return(0,g.y)(function(a){if(this.W)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.Hi(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Ne(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Hi(d,
!0)}}d=VY(a.target);a=new g.Wd(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.ga.M(b,this.g)},a)},L_=function(a){if(a.i||a.l){var b=q_(a.g);
if(b){var c=J_(a);if(a.i){b=d_(b,c);var d=g.QJ(a.A).getVideoContentRect();g.Fi(a.i,b.width,b.height);g.vi(a.i,b.left,b.top);a.K=new g.bi(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=q_(a.g))&&d?YZ(d,e.o,e.g?e.g:"xy"):1;var f=r_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.Zh(d,d,d,d));d=new g.Zh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.QJ(a.A).getVideoContentRect();var p=g.XJ(a.A);g.di(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=K_(a,23,b,d,e);if(a.o){var u=43-f.width;0<u&&(b.left+f.left-u>n.left&&(f.left-=u),f.width+=u)}u=f;g.Fi(a.u,f.width,f.height);g.vi(a.u,f.left,f.top)}a.o&&(u?b=new g.Wd(u.left+
u.width-23-18,a.Z?u.top+2:u.top+u.height-18-2):(u=K_(a,18,b,d,e),b=new g.Wd(u.left,u.top),g.Fi(a.o,u.width,u.height)),g.vi(a.o,b));a.O=new g.bi(a.K.left+u.left,a.K.top+u.top,u.width,u.height);a.N=a.aa.ca(g.QJ(a.A),"mousemove",a.nE,a)}else a.u&&(u=e/f*d.height*4.2/100,u=new g.Zd(u,u),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,u=new g.bi(b.width-u.width-e,b.height-u.height-e,u.width,u.height)):u=new g.bi(b.width-u.width-3*d.height/100,(b.height-u.height)/2,u.width,u.height),g.Fi(a.u,
u.width,u.height),g.vi(a.u,u.left,u.top)),a.o&&(u=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.vi(a.o,u&&e?new g.Wd(b.width-9,-9):u?new g.Wd(b.width-9,45<b.height?9:b.height-9):e?new g.Wd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Wd(45<b.width?b.width-9-18:-9,b.height-9):new g.Wd(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;u=g.QJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
r_(a.g,u)/100+"px";u=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==u||"highlightText"==u?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;u=(b=g.he("annotation-link-icon",a))?XY(b):!1;e=(d=g.he("annotation-close-button",a))?XY(d):!1;u&&g.Hi(b,!1);e&&g.Hi(d,!1);m=f="";if(n=g.he("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Tla(a);p=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+x,k)):l=Math.max(l-x,p),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Hi(d,!0);u&&g.Hi(b,!0)}}}},K_=function(a,b,c,d,e){var f=0<e;
b=new g.bi(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.Z=!0);return b},M_=function(a){return"label"!=a.g.style||a.l.g},J_=function(a){var b=g.QJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.QJ(a.A).getPlayerSize();b=new g.bi(-b.left,-b.top,c.width,c.height)}else b=new g.bi(0,0,b.width,b.height);return new f_(b,a.R?q_(a.R):null)},N_=function(a,b){return b?new g.bi(a.x+b.left,a.y+b.top,b.width,b.height):null},O_=function(a,b,c){g.F.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Vma(b,a)},Vma=function(a,b){Lma(a,function(c){return new t_(a.id,c,b)})},P_=function(a){a.i.unsubscribe("resize",a.nw,a);
a.i.unsubscribe("onVideoAreaChange",a.ey,a)},Q_=function(a){a.g&&(a.g.stop(),a.g=null)},R_=function(a,b,c){kZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},S_=function(a,b,c){kZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=WZ({target:"current",value:a});this.N=b.signin_title||null;this.H=b.signin_message||null},T_=function(a,b,c){S_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.C=b.innertube_request_params},U_=function(a,b,c){kZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},V_=function(a,b,c){kZ.call(this,a,b,c);
this.C=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=WZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},W_=function(a,b,c){S_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new Wma(a[b]))},Wma=function(a){this.merchant=g.Dc(a.merchant);
this.price=g.Dc(a.price)},X_=function(a,b,c){S_.call(this,a,b,c);
this.K=b.ypc_item_type;this.F=b.ypc_item_id;this.C=b.ypc_flow_type},Y_=function(a,b,c){kZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},Z_=function(a,b,c){kZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.C=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=WZ({target:b.target||"new",value:b.url})},Xma=function(a){this.g=a;
this.i={}},Yma=function(a){var b={};
b=(b["iv-event"]=1,b);g.WJ(a.g,"iv",b,void 0)},c0=function(a,b,c,d){if(b){var e=$_(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=a0(a,"cta_annotation_shown",e,c);b0(a,e,Zma(b,d))}},d0=function(a,b,c,d,e,f){if(b){var k=$_(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.rc(k,d);b=a0(a,"cta_annotation_clicked",k,e);b0(a,k,b,c,f)}},e0=function(a,b){if(b){var c=$_(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=a0(a,"cta_annotation_closed",c);b0(a,c,d)}},Zma=function(a,b){return b?(0,g.D)(a,g.Va(function(a,b){return g.Sn(b,a)},b)):a},a0=function(a,b,c,d){d=d?g.ob(d):[];
var e=c["a-type"];if(30==e||31==e&&g.P(g.W(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.vt){if((b=a.vt[b])&&g.yv(b)){a=g.wc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Dm){b=g.Yq(a.Dm,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},b0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(a){f++;
g.Cr(a,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.WJ(a.g,"iv",b,m)},$_=function(a,b){var c={};
if(b){var d=new g.Hn(b);(0,g.A)(d.wd(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.W(a.g).playerStyle;return c},f0=function(a,b,c,d,e){e=$_(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;b0(a,e,d)},g0=function(a,b,c,d){c&&(c=$_(a,c),c["iv-event"]=b,b0(a,c,d))},$ma=function(a,b,c,d,e,f,k){this.i=a;
this.o=b;this.u=c;this.videoData=d;this.logger=e;this.g=f;this.l=k},h0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.Bo},ana=function(a,b){var c=[];
(0,g.A)(b.choices,function(a){c.push({B:"li",G:b.C+"-"+a.index.toString(),I:[{B:"label",I:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.C+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",I:[{B:"span",G:"iv-card-poll-choice-percent"},i0(this,"span",void 0,a.desc)]}]},{B:"div",G:"iv-card-poll-result",I:[{B:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={B:"ul",L:{role:"radiogroup"},I:c},e={};b.o&&(e["aria-label"]=g.LN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",I:[i0(a,"h2",e,b.title),{B:"form",I:[{B:"fieldset",I:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],I:[{B:"h2",U:"Want to vote?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:XZ(b.o)},I:[{B:"span",V:["iv-button-content"],U:"Sign in"}]}]}));f=new g.T({B:"div",
V:f,I:d});d=f.element;j0(b,d);Yla(a.g.i,d,g.Va(a.C,b),a);(0,g.A)(g.ge("iv-card-poll-choice-input",d),function(a){this.g.i.ca(a,"focus",g.Va(this.l,!0));this.g.i.ca(a,"blur",g.Va(this.l,!1))},a);
b.o&&(d=g.he("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Qc,b.l,b.i.click,5));return f},n0=function(a,b,c,d){var e=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=k0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{B:"a",G:"iv-click-target",L:{href:XZ(b.url)},I:[l0(b.imageUrl,e),{B:"div",G:"iv-card-content",I:[i0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({B:"div",V:["iv-card-sign-in"],I:[i0(a,"h2",void 0,b.N||""),{B:"p",U:b.H},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:XZ(b.g)},I:[i0(a,"span","iv-button-content","Sign in")]}]});k=new g.T({B:"div",V:k,I:e});m0(a,k,b,c,d);return k},p0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.C&&b.o?{B:"span",V:d,L:e,U:b.o}:"";c={B:"div",V:["iv-card",c],I:[{B:"a",G:"iv-click-target",L:{href:XZ(b.url)},I:[l0(b.F,d?{B:"div",G:"iv-card-image-text",I:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",I:[{B:"h2",G:"iv-card-primary-link",U:b.title},o0(a,b)]}]}]};c=new g.T(c);m0(a,c,b);return c},q0=function(a,b){return b.customMessage?i0(a,"div","iv-card-message",
b.customMessage):""},l0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},I:d}},o0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(a){c.push(i0(this,"li","",a))},a);
return{B:"ul",G:"iv-card-meta-info",I:c}},i0=function(a,b,c,d){c?g.t(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Co(a.i,d);return{B:b,L:c,U:d}},k0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Co(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,I:e}},j0=function(a,b){var c=0;
(0,g.A)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.he(a.C+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.he("iv-card-poll-choice-percent",f);g.Ie(l,g.LN("$PERCENT%",{PERCENT:k}));f=g.he("iv-card-poll-result-bar",f);g.ni(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.g);g.K(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},r0=function(a,b,c,d){d?(c&&a.g.videoData.oa||a.g.g.pauseVideo(),a.g.g.isFullscreen()&&a.g.g.toggleFullscreen(),d0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.Ft())&&g.ot(a,b.A)):b.url&&a.u(b.url,b.id,b.Qc,b.l,b.i.click||[],5)},m0=function(a,b,c,d,e){c.g&&s0(a,g.ge("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&s0(a,g.ge("iv-click-target",b.element),c,c.url,d)},s0=function(a,b,c,d,e){(0,g.A)(b,function(a){if(e){var b=(0,g.y)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.g.i.ca(a,"click",b)}else d&&this.o(a,d,c.id,c.Qc,c.l,c.i.click,5)},a)},t0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},v0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=u0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},u0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},bna=function(a){a=XZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!v0(a))||(b=g.Gh(g.Fh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.Vq(a);if(!b||!b.v)return null;if(b=b.t)return t0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.Tq(a[1]))&&a.t?t0(a.t):-1},w0=function(a){a=XZ(a);
a=a.replace(/https?:\/\//g,"");return v0(a)?(a=g.Vq(a))&&a.v?a.v:null:null},cna=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},x0=function(a,b){return b?b:v0(a)?"current":"new"},y0=function(a,b){g.F.call(this);
this.Aa=a;this.context=b;this.es=!1;this.ga=0},dna=function(a){return(0,g.C)()-a.ga},ena=function(a,b,c,d,e,f){var k=XZ(b);
if(k){var l=x0(k,b.target),m=(0,g.y)(function(){b.g&&this.context.g.pauseVideo();var a=this.context.videoData.Yb||!1,d=g.Vq(k||"");a&&d&&(d.v||d.list)?g.uX(this.context.g.app,d.v,c,d.list,!1,void 0,void 0):g.eM(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=dna(a);d0(a.context.logger,d,m,n,e,f);v0(k)||(a=g.Ft(),d=c.itct,a&&d&&g.ot(a,g.kt(d)))}},B0=function(a,b,c){y0.call(this,b,c);
var d=this;this.i=a;this.P=null;this.Z=this.wa=this.u=this.sa=!1;this.X=null;this.O=new g.L(g.Ja,c.u.Cc?4E3:3E3);g.H(this,this.O);this.la=new g.L(g.Ja);g.H(this,this.la);this.A=new h0(c,(0,g.y)(this.Yh,this),(0,g.y)(this.Il,this));this.F=new g.T({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},I:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},I:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});
g.H(this,this.F);this.C=this.F.element;this.ea=new g.DP(this.F,330);g.H(this,this.ea);this.xa=g.he("iv-drawer-header-text",this.C);this.o=g.he("iv-drawer-content",this.C);this.l=[];this.na=this.R=this.D=this.W=this.g=null;this.N=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&z0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&A0(d)});
this.K=this.H=this.ba=null},ina=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&C0[c]){c=new C0[c](b.id,b.data,b.g);if(!a.sa){g.Ho(a.ha(),["html5-stop-propagation","iv-drawer-manager"]);g.fK(a.i,a.C,5);fna(a);a.R=g.he("ytp-cards-button",a.i.getRootNode());var d=g.he("iv-drawer-close-button",a.C);a.na=d;a.sa=!0}D0(a,c.id);var e=gna(a,c);if(e){d={Ab:c,ko:e.element,Lv:!1};var f=hna(a,d);g.rb(a.l,f,0,d);e.Y(a.o,f);a.Hk();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Va(a.UK,d)):(e=1E3*a.context.g.getCurrentTime(),5E3>e&&e>c.startMs&&a.bz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Va(a.bz,d)),E0(a))}}},jna=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){z0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){A0(a)});
var c=b.data.headerText;g.Ie(a.xa,c);a.R&&a.R.setAttribute("title",c);b.data.eventId&&(a.P=b.data.eventId);a.ba=g.kt(b.data.trackingParams);a.K=g.kt(b.data.closeTrackingParams);a.H=g.kt(b.data.iconTrackingParams)},D0=function(a,b){var c=kna(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Ab.id),g.Ae(c.ko),g.jb(a.l,c),a.Hk(),E0(a))},z0=function(a,b,c,d){if(!a.u){a.ea.show();
a.W=new g.L(function(){g.J(a.context.g.getRootNode(),"ytp-iv-drawer-open")},0);
a.W.start();a.X=g.fs(a.o,"mousewheel",(0,g.y)(a.PD,a));a.u=!0;a.ga=(0,g.C)();f0(a.context.logger,a.P,7,void 0,d&&d.Ab?d.Ab.l:void 0);var e=g.Ft();e&&a.ba&&a.K&&iZ(e,[a.ba,a.K]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(b){b.Lv||(b.Lv=!0,c0(a.context.logger,b.Ab.l,b.Ab.i.DC,f));e&&iZ(e,[b.Ab.A])});
UY(a.i);c&&(a.D=new g.L(function(){a.ia=a.R;a.na.focus()},330),a.D.start())}},A0=function(a){a.u&&(a.ea.hide(),g.gs(a.X),a.X=null,g.Io(a.context.g.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,UY(a.i),a.D&&a.D.stop(),a.D=new g.L(function(){a.ia&&(a.ia.focus(),a.ia=null)},330),a.D.start())},fna=function(a){var b=g.he("iv-drawer-close-button",a.C);
a.context.i.ca(b,"click",a.oB,a);a.context.i.ca(a.o,"touchend",function(){a.O.start()});
a.context.i.ca(a.o,"scroll",a.vB,a);a.context.l.subscribe("onHideControls",function(){a.Z=!0});
a.context.l.subscribe("onShowControls",function(){a.Z=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Z=g.Go(a.i.getRootNode(),"ytp-autohide")});
a.N.push(g.zq("iv-button-shown",a.XC,a));a.N.push(g.zq("iv-button-hidden",a.WC,a));a.N.push(g.zq("iv-teaser-shown",a.aD,a));a.N.push(g.zq("iv-teaser-hidden",a.ZC,a));a.N.push(g.zq("iv-teaser-clicked",a.YC,a))},gna=function(a,b){switch(b.type){case "simple":return n0(a.A,b);
case "collaborator":var c=a.A,d={B:"div",V:["iv-card","iv-card-channel"],I:[{B:"a",V:["iv-click-target"],L:{href:XZ(b.url),"data-ytid":b.channelId},I:[l0(b.profileImageUrl),{B:"div",G:"iv-card-content",I:[q0(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},o0(c,b)]}]}]};d=new g.T(d);m0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.y)(c.A,c,b),n0(c,b,d,d);case "episode":return p0(a.A,b,"iv-card-episode");case "movie":return p0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={B:"div",V:["iv-card",
"iv-card-playlist"],I:[{B:"a",G:"iv-click-target",L:{href:XZ(b.url)},I:[l0(b.o,{B:"div",G:"iv-card-image-overlay",I:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",I:[q0(c,b),i0(c,"h2","iv-card-primary-link",b.title),o0(c,b)]}]}]},d=new g.T(d),m0(c,d,b),d;case "poll":return ana(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=k0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",I:k});d={B:"div",V:d,L:{tabindex:"0"},I:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:XZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",I:[b.sponsored?{B:"div",G:"iv-card-sponsored",I:["Sponsored",{B:"div",G:"iv-ad-info-container",I:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{B:"div",G:"iv-ad-info-icon-container",I:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:XZ(b.url)},I:[i0(c,"h2",f,b.title),k]}]}]};d=new g.T(d);f=g.ve("span");g.Ie(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ib(f,"adInfo");m0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.y)(c.D,c,b),n0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{B:"span",V:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={B:"div",V:["iv-card","iv-card-video"],I:[{B:"a",G:"iv-click-target",L:{href:XZ(b.url)},I:[l0(b.o,b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",I:[q0(c,b),i0(c,"h2","iv-card-primary-link",b.title),o0(c,b),d]}]}]},d=new g.T(d),m0(c,d,b),d}return null},hna=function(a,b){if(0==a.l.length)return 0;
var c=g.cb(a.l,function(a){return b.Ab.startMs>a.Ab.startMs||b.Ab.startMs==a.Ab.startMs&&b.Ab.timestamp>=a.Ab.timestamp?!0:!1});
return-1==c?0:c+1},lna=function(a){return a.g?"productListing"==a.g.Ab.type:(0,g.kn)(a.l,function(a){return"productListing"==a.Ab.type})},E0=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",lna(a))},F0=function(a,b){if(a.F.Ea()){var c=new dZ([0,
a.o.scrollTop],[0,b.ko.offsetTop],600,Xla);a.context.o.ca(c,"animate",function(b){a.o.scrollTop=b.y});
a.context.o.ca(c,"finish",function(b){a.o.scrollTop=b.y});
c.play()}else g.nC(a.F,!0),a.o.scrollTop=b.ko.offsetTop,g.nC(a.F,!1)},G0=function(a){return a.g&&a.g.Ab?a.g.Ab:a.l[0]&&a.l[0].Ab?a.l[0].Ab:null},kna=function(a,b){return g.bb(a.l,function(a){return a.Ab.id==b})},H0=function(a,b,c){y0.call(this,a,b);
this.annotation=c;this.isActive=!1},mna=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},I0=function(a,b,c){H0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},J0=function(a,b,c){H0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.te("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.L(function(){this.g.setAttribute("aria-hidden",!0);g.Hi(this.l,!1);g.Hi(this.i,!0)},700,this);
g.H(this,this.A)},nna=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ha().setAttribute("aria-hidden",!0);a.ha().setAttribute("aria-label","Promotion");a.ha().tabIndex=0;var e=a.annotation.Hb(),f=b.image_url;if(f){var k=g.te("DIV",["iv-promo-img","iv-click-target"]);f=g.te("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.te("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.te("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Yh(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.te("A","iv-promo-txt"),g.Nd(f,XZ(e)),a.g=f):a.g=g.te("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.te("P",null,g.te("STRONG",null,b.text_line_1));var m=g.te("P",null,g.te("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.u.experiments,"web_center_align_action_cta")&&d.push("iv-promo-website-card-cta-center-aligned");g.P(a.context.u.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.te("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.te("BUTTON",["iv-button","iv-promo-button"],g.te("SPAN","iv-button-content",f));var p=g.te("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Yh(a.ha(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,
"iv-click-target");e&&a.Yh(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=g.te("P",null,g.te("SPAN",null,b.text_line_1)),m=g.te("P",null,g.te("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.te("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.Yh(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);
c=g.te("DIV","iv-promo-actions");a.i=g.te("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.i.ca(a.i,"click",g.Va(a.cp,5E3),a);c.appendChild(a.i);g.Hi(a.i,!1);a.context.i.ca(a.ha(),"mouseover",a.dC,a);a.context.i.ca(a.ha(),"mouseout",a.cC,a);a.context.i.ca(a.ha(),"touchend",g.Va(a.cp,5E3),a);a.l=g.te("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.i.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.VB:a.UB,a);c.appendChild(a.l);g.Ho(a.ha(),d);k&&
(a.ha().appendChild(k),n&&k.appendChild(n));a.ha().appendChild(a.D);a.ha().appendChild(c)},K0=function(a){a.u||a.F||a.o||(g.J(a.ha(),"iv-promo-collapsed"),a.u=!0,a.A.start())},L0=function(a){a.A.stop();
a.u&&(g.Jo(a.ha(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Hi(a.i,!1),g.Hi(a.l,!0))},N0=function(a,b){a.o||(a.o=g.th(function(){M0(this);
K0(this)},b,a))},M0=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},O0=function(a){g.rK.call(this,a);
this.N=!1;this.H=0;this.i={};this.K={};this.D=new Xma(a);this.A=new g.us(this);g.H(this,this.A);this.C=this.l=null;this.A.J(this.player,"onVideoAreaChange",(0,g.y)(this.M,this,"onVideoAreaChange"));this.A.J(this.player,"onHideControls",(0,g.y)(this.M,this,"onHideControls"));this.A.J(this.player,"onShowControls",(0,g.y)(this.M,this,"onShowControls"));this.A.J(this.player,"resize",(0,g.y)(this.M,this,"resize"));this.A.J(this.player,"presentingplayerstatechange",(0,g.y)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.zH,this);this.subscribe("onShowControls",this.BJ,this);this.subscribe("presentingplayerstatechange",this.II,this);this.subscribe("resize",this.Uq,this);this.subscribe("G",this.xD,this);this.subscribe("F",this.eg,this);this.subscribe("D",this.wG,this);this.subscribe("E",this.ZG,this);g.W(this.player).K.subscribe("vast_info_card_add",this.by,this);this.P=new g.us(this);g.H(this,this.P);this.P.J(this.player,g.WD("annotations_module"),this.vD);this.P.J(this.player,
"crx_annotations_module",this.wD);this.R=g.te("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.te("DIV","video-custom-annotations");this.u=new g.T({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.fK(this.player,this.u.element,4);this.u.hide();this.o=new g.T({B:"div",V:["ytp-iv-video-content"]});g.H(this,this.o);g.xe(this.o.element,g.te("DIV","video-annotations",this.R,this.Z));this.F=this.g=null;this.O=[];ona(this)&&this.load();var b=g.ve("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Wf(this,function(){g.Ae(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},P0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},ona=function(a){var b=g.W(a.player);
a=a.player.getVideoData();return 1==(b.Bf||a.Bf)&&!a.Xz||null!==b.K.get(a.videoId)},Q0=function(a,b,c){a.N=!0;
a.C=g.gr(b,c)},R0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(R0(a,e))}return c},S0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},qna=function(a,b){var c=pna(a,b);
if(!c&&"marker"!=b.type)return null;o_(b,function(a){a=(0,g.y)(this.WJ,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new O_(a.ea,b,c);g.H(d,c);return d},rna=function(a,b){var c=g.te("DIV",["annotation",
"annotation-type-custom"]);g.Hi(c,!1);var d=null;switch(b.type){case "branding":if(g.W(a.player).Bc)break;a.u.element.appendChild(c);d=new I0(c,T0(a),b);break;case "promotion":g.fK(a.player,c,4),d=new J0(c,T0(a),b)}d&&d.Ym();return d},sna=function(a){var b=a.player.getVideoData();
if(b.td){var c=g.W(a.player),d=c.K.get(b.videoId);if(d){var e={format:"XML",wc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.wc.gaming="1");e.Pc=(0,g.y)(function(a,b,c){S0(this,a,b)||(a=g.Qq(c)&&c.responseXML?c.responseXML:null)&&U0(this,a)},a,a.H,b.videoId);
g.Vs()&&(e.Pc=V0(a,e.Pc));e.qb={ic_only:"1"};W0(e,d);a.N=!0;g.gr(b.td,e)}}},W0=function(a,b){a.method="POST";
a.qb=a.qb||{};b.Mk&&(a.qb.ic_coll=b.Mk);b.Nk&&(a.qb.ic_xml=b.Nk);b.Pr&&(a.qb.ic_track=b.Pr)},tna=function(a){var b=new g.T({B:"div"});
g.Hi(b.element,!1);var c=new B0(a.player,b.element,T0(a));g.H(c,b);b.Y(a.u.element);c.Ym();return c},T0=function(a){if(!a.F){var b=new hZ(a);
g.H(a,b);var c=new g.Pn(a);g.H(a,c);a.F=new $ma(b,c,g.W(a.player),a.player.getVideoData(),a.D,a.player,a.ea)}return a.F},U0=function(a,b){var c=!1;
una(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=R0(a,d[e]),k=null;try{k=Ima(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=rna(a,k))g.H(a,f),a.K[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=tna(a),g.H(a,a.g)),"card"==k.type?ina(a.g,k):jna(a.g,k),c=!0;else if(f=qna(a,k))g.H(a,f),a.i[k.id]=f}}c&&(UY(a.player),a.Uq());g.Xb(a.i,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.i&&
(b=this.i[b.segment.i])&&(a.R=b.annotation)}},a)},una=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.Ft();
if(b){var c=g.Et();c&&g.mt(b,c,[g.kt(a)])}}},vna=function(a,b,c,d){d?X0(a,b,c):Y0(a,b,c)},Y0=function(a,b,c){if(b=a.i[b])Q_(b),c&&c.i?(a=(0,g.y)(a.qv,a,b),b.g=new g.L(a,2E3),b.g.start()):a.qv(b)},X0=function(a,b,c){if(b=a.i[b])Q_(b),c&&c.o?(a=(0,g.y)(a.lz,a,b),b.g=new g.L(a,2E3),b.g.start()):a.lz(b)},Z0=function(a,b){var c=a.player.getVideoData();
if(!c.Ck)return!1;var d=XZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!v0(d))return!1;d=g.Vq(d);return d.list||d.p?!1:(d=w0(b))?c.videoId==d?!0:"new"!=b.target&&g.W(a.player).i?!0:!1:!1},pna=function(a,b){if(wna(b)){var c=b.u||m_(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new H_(b,(0,g.y)(a.R.appendChild,a.R),a.player,a.ea,c)}return null},wna=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in l_)if(a.style==l_[b])return!0;return!1},$0=function(a,b,c,d){a.M(s_(b,d),c,d)},V0=function(a,b){return(0,g.y)(function(){if(!this.da()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Va.apply(window,a);this.O.push(g.Ts(b))}},a)};
g.KJ.prototype.Xh=g.ca(14,function(a,b){var c=g.LJ(this).l;c&&c.Xh(a,b)});
g.Wo.prototype.Yo=g.ca(0,function(){this.i=this.O.createElement("DIV")});
var Qla=/[^\d]+$/,Rla={cm:1,"in":1,mm:1,pc:1,pt:1},Sla={em:1,ex:1},YY={},ZY=null;g.z(cZ,g.$f);g.z(dZ,g.Lo);g.h=dZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;$Y(this);this.startTime=a=(0,g.C)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Jd("play");-1==this.g&&this.Jd("resume");this.g=1;var b=g.Sa(this);b in YY||(YY[b]=this);aZ();bZ(this,a);return!0};
g.h.stop=function(a){$Y(this);this.g=0;a&&(this.progress=1);eZ(this,this.progress);this.Jd("stop");this.l()};
g.h.pause=function(){1==this.g&&($Y(this),this.g=-1,this.Jd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Jd("destroy");dZ.Ga.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Mq=function(){this.Jd("animate")};
g.h.Jd=function(a){this.dispatchEvent(new cZ(a,this))};
g.z(fZ,dZ);fZ.prototype.u=g.Ja;fZ.prototype.Mq=function(){this.u();fZ.Ga.Mq.call(this)};
fZ.prototype.l=function(){this.u();fZ.Ga.l.call(this)};
fZ.prototype.o=function(){this.u();fZ.Ga.o.call(this)};
g.z(gZ,fZ);gZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.r(hZ,g.F);hZ.prototype.ca=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.fs(a,b,c);this.g.push(a);return a};
hZ.prototype.Jl=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.qs(a,b,c);this.g.push(a);return a};
hZ.prototype.La=function(a){g.gs(a);g.jb(this.g,a)};
hZ.prototype.T=function(){g.gs(this.g);this.g.length=0;g.F.prototype.T.call(this)};g.z(lZ,g.Cg);g.h=lZ.prototype;g.h.To=null;g.h.gj=null;g.h.ha=function(){return this.gj};
g.h.addEventListener=function(a,b,c,d){g.lg(this.gj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.wg(this.gj,a,b,c,d)};
g.h.T=function(){lZ.Ga.T.call(this);var a=this.gj;if(a)if(g.cg(a))a.be&&g.ig(a.be);else if(a=g.og(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.xg(d[e])&&++b}};g.z(qZ,lZ);qZ.prototype.fill=null;g.z(sZ,lZ);tZ.prototype.pe=null;tZ.prototype.ld=null;tZ.prototype.dk=!0;var $la=[2,2,6,6,0];g.h=tZ.prototype;g.h.clear=function(){this.Ua.length=0;this.ya.length=0;this.Fd.length=0;delete this.pe;delete this.ld;delete this.dk;return this};
g.h.moveTo=function(a,b){0==g.Za(this.Ua)?this.Fd.length-=2:(this.Ua.push(0),this.ya.push(1));this.Fd.push(a,b);this.ld=this.pe=[a,b];return this};
g.h.Xb=function(a){var b=g.Za(this.Ua);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ua.push(1),this.ya.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Fd.push(c,d)}this.ya[this.ya.length-1]+=b/2;this.ld=[c,d]};
g.h.close=function(){var a=g.Za(this.Ua);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ua.push(4),this.ya.push(1),this.ld=this.pe);return this};
g.h.clone=function(){var a=new this.constructor;a.Ua=this.Ua.concat();a.ya=this.ya.concat();a.Fd=this.Fd.concat();a.pe=this.pe&&this.pe.concat();a.ld=this.ld&&this.ld.concat();a.dk=this.dk;return a};
g.h.transform=function(a){if(!this.dk)throw Error("Non-simple path");a.transform(this.Fd,0,this.Fd,0,this.Fd.length/2);this.pe&&a.transform(this.pe,0,this.pe,0,1);this.ld&&this.pe!=this.ld&&a.transform(this.ld,0,this.ld,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ua.length};g.z(vZ,qZ);g.z(xZ,g.Wo);xZ.prototype.o=null;xZ.prototype.Wi=function(){return this.Cg?g.Gi(this.ha()):g.Ha(this.width)&&g.Ha(this.height)?new g.Zd(this.width,this.height):null};
xZ.prototype.resume=function(){};g.z(nZ,rZ);g.z(mZ,rZ);g.z(yZ,sZ);yZ.prototype.clear=function(){g.ye(this.ha())};
yZ.prototype.setSize=function(a,b){var c=this.ha(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.z(zZ,vZ);var CZ;g.z(AZ,xZ);var cma=0;g.h=AZ.prototype;g.h.Yo=function(){var a=oZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=oZ(this,"g");this.C=oZ(this,"defs");this.o=new yZ(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ha().setAttribute("preserveAspectRatio","none"),this.R?this.Oz():this.ha().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.N:"")))};
g.h.Oz=function(){if(this.Cg){var a=this.Wi();0==a.width?this.ha().style.visibility="hidden":(this.ha().style.visibility="",this.o.ha().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.N+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Fi(this.ha(),a,b)};
g.h.Wi=function(){if(!g.pi)return this.Cg?g.Gi(this.ha()):AZ.Ga.Wi.call(this);var a=this.width,b=this.height,c=g.t(a)&&-1!=a.indexOf("%"),d=g.t(b)&&-1!=b.indexOf("%");if(!this.Cg&&(c||d))return null;if(c){var e=this.ha().parentNode;var f=g.Gi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ha().parentNode,f=f||g.Gi(e),b=parseFloat(b)*f.height/100);return new g.Zd(a,b)};
g.h.clear=function(){this.o.clear();g.ye(this.C);this.g={}};
g.h.Mi=function(){AZ.Ga.Mi.call(this);this.R&&this.K.La(dma(),"tick",this.Oz)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.K.dispose();delete this.K;AZ.Ga.T.call(this)};g.r(EZ,g.rK);g.h=EZ.prototype;
g.h.load=function(){g.rK.prototype.load.call(this);if(!GZ(g.W(this.player).playerStyle)){var a=g.VB(this.player.getVideoData());if(a)a=DZ(a,FZ(this)),HZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Pc:(0,g.y)(this.qH,this,a),wc:{v:a},withCredentials:!0};"gaming"==g.W(this.player).playerStyle&&(a.wc.gaming="1");this.K&&(a.wc.ptype="embedded");var c=this.player.getVideoData().ou;c&&(a.qb={ad_tracking:c});if(b=g.UB(b))if(b=g.sd(b),b=g.pd(b))this.o=
g.gr(b,a)}}};
g.h.unload=function(){HZ(this,null);this.o&&(this.o.abort(),this.o=null);g.rK.prototype.unload.call(this)};
g.h.Wb=function(a,b){if(!GZ(g.W(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=DZ(b,"new");HZ(this,c);return!0}return null};
g.h.getOptions=function(){return GZ(g.W(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.qH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=DZ(c,FZ(this)))}HZ(this,c)};
g.h.nb=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<a1.length;f++){var k=Math.abs(b.width-a1[f]);if(-1==e||d>=k)e=f,d=k}d=b1[e];this.l&&g.ni(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Fi(e.element,Math.round(k.width*a.width),f);g.vi(e.element,m,n);g.Jo(e.element,xna);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Jo(e.element,b1);g.J(e.element,d);(e=g.fe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ni(e,"height",f+"px")}}}}};
g.h.zD=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.TJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(LZ(this,this.i.impressionUrls),(a=g.Ft())&&g.nt(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");LZ(this,c.impressionUrls);(b=g.Ft())&&g.nt(b,c.visualElement);
g.W(this.player).sb&&this.player.ma("endscreenelementshown",a)}};
g.h.AD=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Io(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Io(b,"ytp-ce-shown");g.W(this.player).sb&&this.player.ma("endscreenelementhidden",a)}};
g.h.lK=function(a){var b=this;a.target===window&&(new g.L(function(){for(var a in b.g)g.Jo(b.g[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Dx=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Go(c,"ytp-ce-element");){g.Go(c,"subscribe-label")&&MZ(this,a);if(g.Go(c,"ytp-ce-channel-subscribe"))return;c=g.Ge(c)}if(!c||g.Go(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Tq(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.en?(MZ(this,a),this.Uy(),this.player.pauseVideo(),c=g.sd(a.targetUrl),c=g.pd(c),g.eM(c,void 0,a.Qc)):(c=this.player.getVideoData().Yb,
c=(0,g.y)(this.aL,this,c,a.targetUrl,a.Qc),c=(0,g.y)(this.Uy,this,c),MZ(this,a,c))}}};
g.h.aL=function(a,b,c){var d=g.Vq(b);a&&d&&(d.v||d.list)?g.uX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.dM(b,c)};
g.h.Zp=function(a,b){g.Go(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.W(this.player).g?(new g.L(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),LZ(this,b.BC),KZ(this,b.id,!0))};
g.h.Tq=function(a,b){g.Io(a.element,"ytp-ce-element-hover");g.Io(a.element,"ytp-ce-force-expand");KZ(this,b.id,!1)};
g.h.Uy=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var a1=[346,426,470,506,570,640,853,1280,1920],b1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),xna=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var oma={BM:"current",JN:"new"};var qma={CLOSE:"close",MN:"openUrl",TA:"subscribe"},rma={vM:"click",CLOSE:"close",eN:"hidden",kO:"rollOut",MA:"rollOver",OA:"shown"};var tma={OO:"xx",PO:"xy",QO:"yx",RO:"yy"};g.r(g_,$Z);var yma={jA:"anchored",gO:"rect",nO:"shapeless"};var Cma={CLOSED:"closed",VN:"playerControlShow",MA:"rollOver",OA:"shown"};k_.prototype.Hb=function(){var a=Kma(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
k_.prototype.showLinkIcon=function(){return m_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var l_={jA:"anchored",mA:"branding",CHANNEL:"channel",AM:"cta",gN:"highlightText",uN:"label",PLAYLIST:"playlist",XN:"popup",rO:"speech",TA:"subscribe",AO:"title",VIDEO:"video",KO:"website"},Gma={mA:"branding",lM:"card",HM:"drawer",fN:"highlight",CN:"marker",cO:"promotion",TEXT:"text",MO:"widget"},Hma={IO:"video_relative",WN:"player_relative"};t_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.ac(this.g,function(a){return a});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};u_.prototype.ha=function(){return this.u};
u_.prototype.l=function(){};var y_={bevel:1,dropshadow:2};g.r(D_,u_);
D_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=p_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.ei(b_(b,c_(e,new g.bi(e.D,e.F,e.ii,e.l),b.g))),k=d.clone();c=new g.bi(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=B_(k,c.effects);l=v_(this,k.width,k.height);m=A_(c,k.width,k.height,this.g);
d=new g.bi(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Wd(f.x-k.left,f.y-k.top);this.o=17*ZZ(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&n_(a),u=p?f.borderWidth+1:f.borderWidth;p=(f=u?new wZ(u,p?f.i:f.borderColor):null)?f.g/2:0;u=Sma(d,n);var x=this.A(d,e,n,u),B=n.x;n=n.y;var E=d.width,G=d.height,S=d.left;d=d.top;var V=new tZ;V.moveTo(S+e+p,d+p);"t"==u&&(V.Xb(x.start,d+p),V.Xb(B,n),V.Xb(x.end,d+p));V.Xb(S+E-e-p,d+p);uZ(V,e,e,-90);"r"==u&&(V.Xb(S+E-p,x.start),V.Xb(B,n),V.Xb(S+
E-p,x.end));V.Xb(S+E-p,d+G-e-p);uZ(V,e,e,0);"b"==u&&(V.Xb(x.end,d+G-p),V.Xb(B,n),V.Xb(x.start,d+G-p));V.Xb(S+e+p,d+G-p);uZ(V,e,e,90);"l"==u&&(V.Xb(S+p,x.end),V.Xb(B,n),V.Xb(S+p,x.start));V.Xb(S+p,d+e+p);uZ(V,e,e,180);V.close();BZ(l,V,f,m);if(m=this.ha())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.vi(m,k.left,k.top),g.Fi(m,k.width,k.height),C_(l,m,c.effects)}}}};
D_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Sd(c-a/2,d+b,d+e-a-b);return new g.Fj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Fj(0,0)};g.r(E_,u_);E_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=B_(d,e.effects);var f=v_(this,c.width,c.height),k=new wZ(!e.l&&this.g?1:e.l,e.bgColor),l=new mZ("#000",0);d=z_(new g.bi(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);BZ(f,d,k,l);f=this.ha();g.J(f,"annotation-shape");e=e.g;WY(f,this.g?Math.max(e,.9):e);g.vi(f,c.left,c.top);g.Fi(f,c.width,c.height)}}};g.r(F_,u_);
F_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=B_(d,c.effects),f=v_(this,e.width,e.height),k=new g.bi(0,0,d.width,d.height);d=A_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&n_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new wZ(p,n?m.i:m.borderColor):null;k=z_(k,l,m?m.g/2+1:0);BZ(f,k,m,d);if(k=this.ha())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.vi(k,e.left,e.top),g.Fi(k,e.width,e.height),C_(f,k,c.effects)}}};g.r(G_,D_);G_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new g.Fj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Fj(0,0)};g.r(H_,g.F);g.h=H_.prototype;g.h.ow=function(){this.F||(this.o&&g.Hi(this.o,!0),this.u&&g.Hi(this.u,!0),this.l&&(this.l.g=!0,WY(this.i,M_(this)?1:0),this.l.l(this.g,J_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Jl(g.QJ(this.A),"mouseleave",function(a){this.lm.stop();this.eg(a)}))};
g.h.eg=function(){this.F&&(this.O?this.D.start():this.rv(),this.l&&(this.l.g=!1,WY(this.i,M_(this)?1:0),this.l.l(this.g,J_(this))),this.F=!1,this.H&&(this.aa.La(this.H),this.H=null))};
g.h.rv=function(){this.o&&g.Hi(this.o,!1);this.u&&g.Hi(this.u,!1)};
g.h.nE=function(a){this.X=a;this.lm.ej()};
g.h.bC=function(){var a=this.X,b=new g.Wd(a.clientX,a.clientY),c=g.zi(this.A.getRootNode()),d=N_(c,this.K);c=(this.u&&XY(this.u)||this.o&&XY(this.o))&&N_(c,this.O);d&&d.contains(b)||c&&c.contains(b)?this.ow(a):this.eg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=J_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new E_:"popup"==this.g.style?d=new F_:"anchored"==this.g.style?d=new D_:"speech"==this.g.style&&(d=new G_);d&&(d.l(this.g,c),this.l=d,c=d.ha())&&(g.Hi(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.P(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.te("DIV",c);g.Hi(this.i,!1);this.g.o&&(this.C=g.te("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.i.bgColor),g.Ie(this.C,this.g.o),this.i.appendChild(this.C));g.pq(this.i,"annotation_id",this.g.id);this.P(this.i);Tma(this,this.i);if(n_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Hb())c=this.i,d=new g.Bn(XZ(d)),c.title=d.g+d.i;this.u=g.te("SPAN","annotation-link-icon");g.Hi(this.u,
!1);this.i.appendChild(this.u)}Uma(this);n_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=i_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ha()&&(this.l.ha().style.zIndex=a)}g.Hi(this.i,!0);WY(this.i,M_(this)?1:0);L_(this);this.l&&this.l.ha()&&g.Hi(this.l.ha(),!0)};
g.h.hide=function(){this.i&&g.Hi(this.i,!1);this.l&&this.l.ha()&&g.Hi(this.l.ha(),!1);this.N&&(this.aa.La(this.N),this.N=null)};g.r(O_,g.F);g.h=O_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(P_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.nw,this),this.i.subscribe("onVideoAreaChange",this.ey,this))};
g.h.destroy=function(){if(this.view){P_(this);var a=this.view,b=a.aa;g.gs(b.g);b.g.length=0;a.lm.dispose();a.D.dispose();a.i&&g.Ae(a.i);a.l&&a.l.ha()&&g.Ae(a.l.ha())}Q_(this)};
g.h.ey=function(){L_(this.view)};
g.h.nw=function(){L_(this.view)};g.r(R_,kZ);g.r(S_,kZ);g.r(T_,S_);g.r(U_,kZ);g.r(V_,kZ);g.r(W_,S_);g.r(X_,S_);g.r(Y_,kZ);g.r(Z_,kZ);h0.prototype.l=function(a,b){var c=g.Ne(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
h0.prototype.C=function(a,b){var c=g.Ne(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.he("iv-card-sign-in-button",c).click();else{var d=parseInt(Ula(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;j0(a,c);g.kr(this.g.videoData.td,{wc:{action_poll_vote:1},qb:{poll_id:a.id,index:d,session_token:a.F}});d0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.Ft())&&g.ot(c,a.A)}};
h0.prototype.A=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.C)});
r0(this,a,!0,c)};
h0.prototype.D=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Va(b,a.K,a.F,a.C));r0(this,a,!1,b)};g.r(y0,g.F);g.h=y0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.TD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&TY(a).subscribe("onEnter",d,this);e&&TY(a).subscribe("onExit",e,this);g.ZJ(this.context.g,[a])};
g.h.Ym=function(){this.context.l.subscribe("resize",this.Hk,this)};
g.h.ha=function(){return this.Aa};
g.h.Yh=function(a,b,c,d,e,f,k){this.context.i.ca(a,"click",g.Va(this.Il,b,c,d,e,f||[],k||0),this);this.context.i.ca(a,"touchstart",g.Va(function(){this.es=!1}),this);
this.context.i.ca(a,"touchmove",g.Va(function(){this.es=!0}),this)};
g.h.Il=function(a,b,c,d,e,f,k){if(this.es)return!1;k&&(k.stopPropagation(),k.preventDefault());ena(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ga=(0,g.C)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Ae(this.ha())};
g.h.Hk=function(){};g.r(B0,y0);g.h=B0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Gi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Hk=function(){var a=this.isAvailable();g.Hi(this.ha(),a);g.K(this.context.g.getRootNode(),"ytp-iv-drawer-enabled",a);UY(this.i)};
g.h.destroy=function(){this.i.Xh(!1);this.i.getRootNode().removeChild(this.C);g.Aq(this.N);g.gs(this.X);this.W&&this.W.dispose();this.D&&this.D.dispose();y0.prototype.destroy.call(this)};
g.h.PD=function(a){this.O.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.bz=function(a){if(!g.Go(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.Ft(),c=this.g?this.g.Ab.u:this.H;b&&c&&jZ(b,[c]);this.g=a;E0(this)}XY(this.ha())&&(2==this.context.g.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.g.getAdState():void 0):(b=isNaN(void 0)?this.context.g.getPlayerState():void 0,b=1==b||0==b&&0===this.context.g.getCurrentTime()),b&&a.Ab.teaserDurationMs&&this.i.Xh(!0,{teaserText:a.Ab.teaserText,durationMs:a.Ab.teaserDurationMs}));this.la.isActive()||
((!this.u||!this.O.isActive()&&this.Z)&&F0(this,a),this.la.start(910+a.Ab.teaserDurationMs))}};
g.h.UK=function(a){this.u||(this.g=a,E0(this),F0(this,a),z0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.oB=function(){if(this.u){f0(this.context.logger,this.P,4,G0(this).i.close);var a=g.Ft();a&&this.K&&g.ot(a,this.K);A0(this)}};
g.h.vB=function(){g.K(this.C,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.XC=function(){var a=g.Ft(),b=G0(this);b=b?b.u:this.H;a&&b&&iZ(a,[b])};
g.h.WC=function(){var a=g.Ft(),b=G0(this);b=b?b.u:this.H;a&&b&&jZ(a,[b])};
g.h.aD=function(){var a=G0(this);g0(this.context.logger,8,a.l,a.i.fL);var b=g.Ft();b&&a&&iZ(b,[a.D,a.u])};
g.h.ZC=function(){var a=g.Ft(),b=G0(this);a&&b&&jZ(a,[b.D])};
g.h.YC=function(a){var b=G0(this),c=g.Ft();this.g?a?(a=this.context.logger,g0(a,9,b.l,b.i.Lr),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.ot(c,b.D)):(a=this.context.logger,g0(a,12,b.l,b.i.Lr),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.ot(c,b.u)):(a=this.context.logger,f0(a,this.P,12,b.i.Lr),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.ot(c,this.H))};
var C0={collaborator:R_,donation:T_,episode:Z_,movie:Z_,playlist:U_,poll:V_,productListing:W_,simple:S_,tip:X_,video:Y_};g.r(H0,y0);H0.prototype.Ym=function(){y0.prototype.Ym.call(this);mna(this)};
H0.prototype.show=function(){y0.prototype.show.call(this);var a=g.Ft(),b=this.annotation.data;a&&b&&(b=b.session_data)&&iZ(a,[g.kt(b.itct)])};
H0.prototype.hide=function(){y0.prototype.hide.call(this);var a=g.Ft(),b=this.annotation.data;a&&b&&(b=b.session_data)&&jZ(a,[g.kt(b.itct)])};g.r(I0,H0);g.h=I0.prototype;g.h.bL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Gi(a);this.g||(g.Ei(a,e.width),g.Ei(b,e.width));g.ni(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ni(c,"right","1px");this.o=!0;g.Hi(a,!0);this.A=new g.L(function(){g.J(this.ha(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.AC=function(a,b){g.Io(this.ha(),"iv-branding-active");this.C=new g.L((0,g.y)(function(){g.Hi(a,!1);this.g||g.Ei(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){H0.prototype.show.call(this);if(!this.D){g.J(this.ha(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.te("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Hi(this.i,!1);var b=g.te("DIV","branding-img-container",this.i);this.ha().appendChild(b);var c=g.te("DIV","iv-branding-context-name");g.Ie(c,a.channel_name);var d=g.te("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.pV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.g),this.g.Y(d);b=g.te("DIV","iv-branding-context-subscribe-caret");c=g.te("DIV","branding-context-container-inner",b,c,d);g.Hi(c,!1);d=g.te("DIV","branding-context-container-outer",c);g.ni(d,"right",this.u+"px");this.ha().appendChild(d);var e=this.annotation.Hb();e&&this.Yh(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.L(g.Va(this.AC,c,d),500,this);g.H(this,this.l);this.context.i.ca(this.ha(),"mouseover",(0,g.y)(this.bL,this,c,d,b,a.image_height));this.context.i.ca(this.ha(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}c0(this.context.logger,this.annotation.g);g.Hi(this.ha(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=VY(a).width;c=g.Ha(void 0)?void 0:b;g.vi(a,c);f=new gZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Wla);g.H(this,f);this.context.o.ca(f,
"begin",g.Va(g.Hi,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(H0.prototype.hide.call(this),g.Hi(this.ha(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);H0.prototype.destroy.call(this)};g.r(J0,H0);g.h=J0.prototype;g.h.show=function(){this.isActive||(H0.prototype.show.call(this),this.H||(nna(this),this.H=!0),g.Hi(this.ha(),!0),this.annotation&&this.annotation.g&&c0(this.context.logger,this.annotation.g),g.th(function(){g.Io(this.ha(),"iv-promo-inactive")},100,this),this.ha().removeAttribute("aria-hidden"),this.isActive=!0,M0(this),L0(this),N0(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ha(),"iv-promo-inactive"),this.isActive=!1,this.ha().setAttribute("aria-hidden",!0))};
g.h.Il=function(a,b,c,d,e,f,k){return this.u?!1:H0.prototype.Il.call(this,a,b,c,d,e,f,k)};
g.h.cp=function(a,b){b.stopPropagation();L0(this);N0(this,a);this.g.focus()};
g.h.dC=function(a){this.F=!0;this.cp(500,a)};
g.h.cC=function(){this.F=!1;K0(this)};
g.h.UB=function(a){a.stopPropagation();this.hide();e0(this.context.logger,this.annotation.g)};
g.h.VB=function(a){a.stopPropagation();M0(this);this.u=!0;g.J(this.ha(),"iv-promo-collapsed-no-delay");this.A.start();e0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();H0.prototype.destroy.call(this)};g.r(O0,g.rK);g.h=O0.prototype;g.h.Wb=function(a,b){if(!P0(g.W(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Ko(b);c&&U0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(D0(this.g,b),UY(this.player)),!0}return null};
g.h.getOptions=function(){return P0(g.W(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Uq=function(){if(this.o){var a=g.QJ(this.player).getVideoContentRect(!0);g.Fi(this.o.element,a.width,a.height);g.vi(this.o.element,a.left,a.top)}if(this.g){var b=g.XJ(this.player);a=this.g;b=b.width;g.K(a.C,"iv-drawer-small",426>=b);g.K(a.C,"iv-drawer-big",1280<=b)}};
g.h.II=function(a){this.ac(a.state);g.U(a.state,2)&&(this.jd()&&this.ne()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Xh(!1))};
g.h.load=function(){g.rK.prototype.load.call(this);this.ac(g.PJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.rH,this,b,this.H),d=(0,g.y)(function(){this.C=null},this);
g.Vs()&&(c=V0(this,c));c={format:"XML",Pc:c,onError:d,wc:{}};a.isPharma&&(c.wc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.W(this.player);"gaming"==d.playerStyle&&(c.wc.gaming="1");(b=d.K.get(b))&&W0(c,b);b=b&&(b.Nk||b.Mk);if(!a.Bk||b)a.td?Q0(this,a.td,c):(this.l=(0,g.y)(this.yD,this,c),this.player.addEventListener("videodatachange",this.l));g.fK(this.player,this.o.element,4);this.Uq()};
g.h.ac=function(a){a=!g.nD(a)&&!g.U(a,1024);g.nC(this.u,a);g.nC(this.o,a)};
g.h.yD=function(a){var b=this.player.getVideoData();b.td&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),Q0(this,b.td,a))};
g.h.unload=function(){Yma(this.D);g.bK(this.player,"annotations_module");g.Xb(this.i,function(a){a.destroy()});
g.Xb(this.K,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,UY(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.K={};this.u.hide();g.rK.prototype.unload.call(this);g.mC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.rH=function(a,b,c){this.C=null;if(!S0(this,b,a)&&(a=g.Qq(c)&&c.responseXML?c.responseXML:null)){U0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.TD(c,e,f);a.push(b)}}g.ZJ(this.player,a)}};
g.h.by=function(a){a==this.player.getVideoData().videoId&&(this.loaded?sna(this):this.load())};
g.h.vD=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,X0(this,a),c0(this.D,b.g))};
g.h.wD=function(a){Y0(this,a.getId())};
g.h.qv=function(a){a&&(a.hide(),$0(this,"shown",!1,a.annotation.id),this.Wk(a.annotation,"hidden"))};
g.h.lz=function(a){a&&(a.show(),$0(this,"shown",!0,a.annotation.id),this.Wk(a.annotation,"shown"))};
g.h.WJ=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;o_(d.annotation,function(a){e=e||a.value});
vna(this,a,b,e)}};
g.h.wG=function(a){if(a&&a.id){var b=a.Hb();if(b){var c=XZ(b);if(c){var d=(0,g.y)(this.Wk,this,a,"click");if("new"==x0(c,b.target)||Z0(this,b))d(),d=null;d0(this.D,a.g,d)}}}};
g.h.Wk=function(a,b){Jma(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!Z0(this,c.url))){e=w0(c.url);var f=bna(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=T0(this).g,g.uX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&T0(this).g.Zb()&&T0(this).g.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.W(this.player),(d=XZ(c.url))?(f=u0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Va(cna,e.pageId,e.xc),d=new g.Bn(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=x0(d,c.url.target),e=a.itct,"ei"in g.Vq(d)&&(d=g.Wh(d,"ei")),g.eM(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.zH=function(){$0(this,"playerControlShow",!1)};
g.h.BJ=function(){$0(this,"playerControlShow",!0)};
g.h.xD=function(a){$0(this,"rollOver",!0,a.id)};
g.h.eg=function(a){$0(this,"rollOver",!1,a.id)};
g.h.ZG=function(a){a&&a.id&&(this.i[a.id].l=!0,Y0(this,a.id),e0(this.D,a.g),this.Wk(a,"close"),$0(this,"closed",!0,a.id))};
g.h.jd=function(){return!!this.g&&this.g.isAvailable()};
g.h.ne=function(){this.jd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.jd();this.g&&(a?c?z0(this.g,c,b):z0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):A0(this.g))};
g.h.Xh=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.W(this.player).K.unsubscribe("vast_info_card_add",this.by,this);g.Io(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.O,b=0,c=a.length;b<c;b++)g.Ws(a[b]);this.O.length=0;g.rK.prototype.T.call(this)};g.vU.annotations_module=O0;g.vU.creatorendscreen=EZ;})(_yt_player);
