(function(g){var window=this;var c1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Jz(a),kind:a.o,name:a.u,id:a.Da,is_servable:a.F,is_default:a.isDefault,is_translateable:a.C,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},d1=function(a){return a.g?a.g.languageCode:a.i},yna=function(a,b){var c=new g.Iz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.A=a.A;c.D=a.D;c.g=b;return c},e1=function(a){if(!zna.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Ana,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Bna=function(){this.i=[];
this.g=[]},f1=function(a,b){return b?a.g.concat(a.i):a.g},g1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.bb(c,(0,g.y)(b.bq,b))||c.push(b);break;default:c=a.g,g.bb(c,(0,g.y)(b.bq,b))||c.push(b)}},h1=function(){g.F.call(this);
this.i=new Bna;this.u=[]},i1=function(a,b,c){h1.call(this,a);
this.g=null;this.u=b.Dt;this.l=c},j1=function(){this.Ua=[]},k1=function(a,b,c,d,e,f){g.F.call(this);
this.N=a;this.o=b;this.A=new j1;this.g=null;this.F=d;this.K=f;this.i=this.l=null;this.D=c;this.C=e||!1;this.H=new g.L(this.Kv,1E3,this);g.H(this,this.H);this.u=new g.us(this);g.H(this,this.u);g.P(g.W(b).experiments,"html5_disable_captions_seek_complete")?this.u.J(b,"seekto",this.ww):this.u.J(b,"seekcomplete",this.yE);this.ww(b.getCurrentTime());this.Kv()},l1=function(a,b){b-=a.o.qc();
var c=a.g;a.g=g.Za(a.D.se(b).g);c!=a.g&&a.K&&a.K()},m1=function(a,b){var c=g.Zv(b,a.N,{}).Hb(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.Hr(c,d,3,100).then((0,g.y)(a.hJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.wb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.ib(c.Ua,e),g.ib(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.rb(c.Ua,e,0,d),g.rb(c.Ua,e+1,0,d)))},n1=function(a,b){h1.call(this,g.W(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.tz(g.W(this.C))&&!this.g.i},o1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.oU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Iz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Cna=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},p1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.oU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},q1=function(a,b,c,d,e){h1.call(this,e||null);
c=c||g.Vq(a).hl||"";c=c.split("_").join("-");this.o=g.Yq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},r1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.TD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},s1=function(a,b,c,d,e){g.TD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},u1=function(a){a=void 0===a?{}:a;
var b="_"+t1++;return new s1(0,0x8000000000000,0,b,a)},w1=function(a,b,c,d,e,f,k){var l={};
g.Wa(l,b);g.Wa(l,a.params);g.Wa(l,c);var m={};g.Wa(m,b.tb);a.params.tb&&g.Wa(m,a.params.tb);g.Wa(m,c.tb);l.tb=m;g.T.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==l.hg?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},I:[{B:"span",G:"captions-text"}]});this.o=[];this.X=!1;this.l=a;this.D=[];this.K=[];this.Sa=e;this.Qa=f;this.Oa=k;this.A=this.H=null;this.ea=.96*e;this.wa=.96*f;this.i=l;this.Fa=c;this.u=this.g["captions-text"];this.Aa=null!=this.u.style["box-decoration-break"]||
null!=this.u.style["-webkit-box-decoration-break"];this.W=d/360*16;this.type=0;this.la=this.W*v1(m);a=new g.As(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.xE,this);a.subscribe("dragmove",this.wE,this);a.subscribe("dragend",this.vE,this);this.sa=this.na=0;b="";this.i.windowOpacity&&(a=e1(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":Dna[this.i.textAlign]};this.Aa&&(a["border-radius"]=
b?this.la/8+"px":"");if(this.C=!g.P(this.Oa,"web_player_vertical_and_ruby_captions_killswitch")&&(2==this.l.params.hg||3==this.l.params.hg))b=this.element,c="vertical-rl",1==this.i.vz&&(c="vertical-lr"),g.ne&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.ni(b,"-o-writing-mode",c),g.ni(b,"-webkit-writing-mode",c),g.ni(b,"writing-mode",c),g.ni(b,"text-orientation","upright"),3==this.l.params.hg&&(g.ni(b,"text-orientation",""),g.ni(b,"transform","rotate(180deg)"));g.ni(this.element,a);switch(this.i.Af){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},v1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},x1=function(a,b){var c={},d=b.background?b.background:a.i.tb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.tb.backgroundOpacity;d=e1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*v1(b)+"px";d=1;e=b.color||a.i.tb.color;if(b.color||null!=b.textOpacity)e=e1(e),d=null==b.textOpacity?a.i.tb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Lt&&(k=e=b.Lt);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=u;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.pr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.tb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ae&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.sl&&(c.visibility="hidden");return c},y1=function(a,b,c){a.X=a.X||!!c;
var d={};g.Wa(d,a.i.tb);g.Wa(d,c||b.i);g.Wa(d,a.Fa.tb);c=a.D[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.sl==!!c.sl&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.D.length;e++)if(g.nc(d,a.D[e])){var f=a.K[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ve("SPAN");g.ni(f,x1(a,e));a.K[0].appendChild(f);e=1}a.K.length=e;a.D.length=e}else a.K.length=0,a.D.length=0,f=g.ve("SPAN"),g.ni(f,x1(a,d)),a.u.appendChild(f);k=!d.sl;e=(c=g.t(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.o.length||!b.l){if(0<l||0!=a.o.length){var n=g.ve("BR");f.appendChild(n)}k&&a.vo(f)}m&&(k?a.H:f).appendChild(c?g.we(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.ni(k[c],x1(a,d)),g.ni(k[c],"font-size","50%");a.D.push(d);a.K.push(f);a.o.push(b)},z1=function(){},B1=function(){this.o=this.i=this.mode=this.l=0;
this.u=new A1(this);this.A=new A1(this);this.g=[];this.clear()},Ena=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ek:a,
Fk:b,result:0};a=C1[a];b=C1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Ek:a,Fk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ek:a,Fk:b,result:2};return{Ek:a,Fk:b,result:3}},Fna=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,D1(a.u,b,c,d))},Gna=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Fna(a,d.Ft,d.Gt,b):1==d.type&&a.l&496&&D1(a.A,d.Ft,d.Gt,b)}a.g.length=0},E1=function(){this.g=0},F1=function(){this.i=this.l=this.g=0},G1=function(){this.timestamp=this.Dd=0},H1=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new G1}this.g=this.i=this.row=0;this.style=new E1;this.u=a;this.o=0},I1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var u=a.l[m][p];
if(0!=u.Dd){0==c&&(c=m,d=p);n=String.fromCharCode(u.Dd);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Dd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],u=p.Dd,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=p.timestamp,x<=e&&(e=x),l+=n,p.reset()),32==m||0==u)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Lna=function(a,b){switch(a){case 0:return Hna[(b&127)-32];
case 1:return Ina[b&15];case 2:return Jna[b&31];case 3:return Kna[b&31]}return 0},J1=function(a){return a.l[a.row][a.i]},K1=function(a,b,c){2<=b&&1<a.i&&(--a.i,J1(a).Dd=0);
var d=J1(a);d.timestamp=a.u.i+0;d.Dd=Lna(b,c);32>a.i&&a.i++},L1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].If(a.l[c+e][f])},M1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},N1=function(a){a.row=0<a.g?a.g:1;
a.i=1;M1(a,0,15)},O1=function(a){this.o=a;
this.u=0;this.style=new E1;this.A=new H1(a);this.C=new H1(a);this.D=new H1(a);this.i=this.A;this.l=this.C;this.g=this.i},P1=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:I1(d,c),N1(a.i),N1(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(I1(d,c),M1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},Q1=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},R1=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},A1=function(a){this.i=a;
this.g=new F1;this.u=0;this.l=new O1(a);this.A=new O1(a);this.o=this.l},D1=function(a,b,c,d){a.g.update();
b=Ena(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ek;c=b.Fk;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&K1(a,0,b),c&96&&K1(a,0,c),0!=b&&0!=c&&3==a.style.g&&I1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;L1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));M1(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:K1(b.g,0,32);break a;case 48:57==c?(b=b.g,J1(b).Dd=0,32>b.i&&b.i++):K1(b.g,1,c&15)}break;case 2:c&32&&K1(b.g,2,c&31);break;case 3:c&32&&K1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Q1(b);break;case 33:b=
b.g;1<b.i&&(--b.i,J1(b).Dd=0);break;case 36:b=b.g;d=J1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.l[a][c]==d){for(;32>=c;c++)b.l[a][c].reset();break}break;case 37:P1(b,2,d);break;case 38:P1(b,3,d);break;case 39:P1(b,4,d);break;case 40:K1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);N1(d);R1(b);break;case 43:R1(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:I1(a,d)}M1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;I1(a,d);L1(a,b,b+1,a.g-1);M1(a,a.row,1)}break;case 46:M1(b.l,0,15);break;case 47:I1(b.i,d);d=b.l;a=b.o.i+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.l[c][e].timestamp=a;d=b.l;b.l=b.i;b.i=d;Q1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.i+=c&3)&&(b.i=32)}}},S1=function(a){g.F.apply(this,arguments)},T1=function(a,b){S1.call(this);
this.N=b;this.o={};this.F={};this.H={};this.u="_"+t1++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},U1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},V1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},W1=function(a,b){var c=U1(a,b);
return void 0!=c?c:null},Y1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return X1.test(c),c},Z1=function(a,b){var c={},d=b.getAttribute("ws");
g.Wa(c,d?a.H[d]:a.A);d=W1(b,"mh");null!=d&&(c.Vp=d);d=W1(b,"ju");null!=d&&(c.textAlign=d);d=W1(b,"pd");null!=d&&(c.hg=d);d=W1(b,"sd");null!=d&&(c.vz=d);d=Y1(b,"wfc");null!=d&&(c.windowColor=d);d=U1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},$1=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Wa(c,a.F[d]);d=W1(b,"ap");null!=d&&(c.Af=d);d=U1(b,"cc");null!=d&&(c.Qt=d);d=U1(b,"ah");null!=d&&(c.Ce=d);d=U1(b,"rc");null!=d&&(c.rr=d);d=U1(b,"av");null!=d&&(c.jg=d);return c},a2=function(a,b,c,d){var e={};
g.Wa(e,$1(a,b));g.Wa(e,Z1(a,b));d?g.nc(e,a.A)?(d=a.u,e=a.A):d="_"+t1++:d=b.getAttribute("id")||"_"+t1++;a=U1(b,"t")+c;b=U1(b,"d")||0x8000000000000;return new s1(a,b,0,d,e)},b2=function(a,b,c,d,e,f,k){w1.call(this,a,b,c,d,e,f,k);
this.type=1},c2=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},d2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},e2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},f2=function(a,b){S1.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new B1;this.g.l=1<<this.track},h2=function(a){if(g.t(a))return!1;
a=new c2(a,8,0);return g2(a)},g2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=e2(a))return!1;
a.version=d2(a);if(1<a.version)return!1;d2(a);d2(a);d2(a);return!0},i2=function(a,b,c,d,e,f,k){w1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.R=this.O=this.ba=0;this.P=NaN;this.xa=0;this.Ca=null;this.ia=new g.L(this.mJ,433,this);g.H(this,this.ia)},Mna=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},Nna=function(a){if(isNaN(a.P)){var b=a.i.Qt;
if(b){var c=g.ve("SPAN");g.Ie(c,"\u2013".repeat(b));g.ni(c,x1(a,a.i.tb));a.u.appendChild(c);a.P=c.offsetWidth;a.u.removeChild(c)}else a.P=0}return a.P},Ona=function(a,b){if(!b)return"";
a.C&&1!=a.l.params.vz&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},j2=function(a){a.F=Array.prototype.slice.call(g.ge("ytp-rollup-caption-line-wrapper"));
for(var b=a.l.params.rr,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.O=d;a.R=Math.max(Nna(a),a.xa,Mna(a,a.u))},Pna=function(a,b){j2(a);
var c=a.F.reduce(function(b,c){return(a.C?c.offsetWidth:c.offsetHeight)+b},0);
c=a.O-c;if(c!=a.ba){var d=0<c&&0==a.ba;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.Ro(a.ia));g.ni(a.u,"transform",Ona(a,c));a.ba=c}j2(a)},k2=function(){S1.call(this)},l2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ae=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new r1(b,c,d,e.id,p.nodeValue,f||0<n,g.jc(l)?void 0:l);m.push(p);var u=e;g.H(u,p);u.i.push(p)}else u={},g.Wa(u,l),l2(a,b,c,d,e,!0,p,u,m)}},m2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},n2=function(a,b,c,d){d=Object.assign({Vp:0},d);
return new s1(a,b,c,"_"+t1++,d)},o2=function(a){g.F.call(this);
this.i=a;this.g=null},r2=function(a){g.rK.call(this,a);
this.l=g.W(a);this.o=a.getVideoData();this.wa=g.QJ(a);this.N=a;var b=null,c=g.Dp("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.np(c));this.X=b;this.u={tb:{}};this.A={tb:{}};this.H=[];this.O={};this.Z={};this.K=!1;this.na=g.pU(this.o,this.N);this.xa=!!this.o.captionTracks.length;this.Fa=!!this.o.Ei;this.la="3"==this.l.o;b=a.app.u;c=!(!b||!b.gk());this.sa=!(!b||!b.Yg());this.C=this.la&&c&&!this.na;this.P=!this.C&&this.la&&this.sa&&this.na;this.i=this.D=this.F=this.R=this.ia=null;this.W=
new o2(this.l);g.H(this,this.W);this.Aa=g.P(this.l.experiments,"web_player_subtitles_get_display_settings_killswitch");this.Ca=g.P(this.l.experiments,"web_player_subtitles_set_display_settings_killswitch");c=b=this.g=null;this.C||(b=new g.Oo(this.Mz,void 0,this),g.H(this,b),c=new g.L(this.IK,2E3,this),g.H(this,c));this.ga=b;this.ba=c;this.aa=new g.us(this);g.H(this,this.aa);this.C||this.aa.J(a,"resize",this.Ur);this.aa.J(a,"onPlaybackAudioChange",this.FG);this.aa.J(a,g.WD("captions"),this.HD,this);
this.aa.J(a,"crx_captions",this.ID,this);p2(this,q2(this,"display-settings")||{})},s2=function(a){if(1==a.l.Ef||1==a.o.Ef||"alwayson"==g.LB(a.o,"yt:cc"))return!0;
if(2==a.l.Ef){var b=q2(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.player.getAudioTrack().jo;return"ON"==c||"on"==g.LB(a.o,"yt:cc")},t2=function(a,b){if(a.g&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Zk||"FORCED_ON"==c.jo},v2=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Fa?!1:a.xa?!1:!0);c=f1(a.i.i,c);for(var d=[a.o.Df,a.l.Df,g.LB(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d1(c[f])==d[e])return c[f];return a.D&&a.D.xo?a.D.xo:(d=c.find(function(a){return a.isDefault}))?d:c[0]||u2(a)}return null},u2=function(a){return a.D&&a.D.Zk},w2=function(a){var b=u2(a);
return!!b&&a.g==b},x2=function(a,b){for(var c=a.N.app.u.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},z2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&y2(a,"module-enabled",!!b));a.g=b;t2(a)&&(a.g=u2(a));a.load()},Qna=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Vp?b.params.Vp:1<b.i.length?1:0){case 1:return new b2(b,a.u,a.A,c,d.width,d.height,a.l.experiments);case 2:return new i2(b,a.u,a.A,c,d.width,d.height,a.l.experiments);default:return new w1(b,a.u,a.A,c,d.width,d.height,a.l.experiments)}},p2=function(a,b,c){var d=A2.tb;
a.u={};g.Wa(a.u,A2);a.u.tb={};g.Wa(a.u.tb,d);a.A={tb:{}};var e=b.backgroundOverride?a.A:a.u,f=b.background||d.background;X1.test(f);e.tb.background=f;e=b.colorOverride?a.A:a.u;f=b.color||d.color;X1.test(f);e.tb.color=f;e=b.windowColorOverride?a.A:a.u;f=b.windowColor||A2.windowColor;X1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.u;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.tb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.u;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.tb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.u;e=b.fontStyle;null==e&&(e=d.bold&&d.Ae?3:d.bold?1:d.Ae?2:0);f=f.tb;switch(e){case 1:f.bold=!0;delete f.Ae;break;case 2:delete f.bold;f.Ae=!0;break;case 3:f.bold=!0;f.Ae=!0;break;default:delete f.bold,delete f.Ae}e=b.textOpacityOverride?a.A:a.u;f=b.textOpacity;null==f&&(f=d.textOpacity);e.tb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.u;f=b.windowOpacity;null==f&&(f=A2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.u;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.tb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.u;f=b.fontFamily;null==f&&(f=d.fontFamily);e.tb.fontFamily=f;a.loaded&&a.Ur();c&&y2(a,"display-settings",b)},C2=function(a,b){if(b&&!a.F){var c=u1({hg:0,
lang:"en"});a.F=[c,new r1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.ZJ(a.player,a.F)}else!b&&a.F&&(B2(a,a.F),a.F=null)},B2=function(a,b){g.aK(a.player,b);
(0,g.A)(b,function(a){g.jb(this.H,a)},a);
a.ga.dj()},D2=function(a,b){return a&&g.t(a)&&X1.test(a)?a:b},E2=function(a,b){return g.Ha(a)&&!isNaN(a)?Math.max(0,Math.min(1,parseFloat(a))):b},Rna=function(a,b){return g.Ha(a)&&!isNaN(a)?g.Sd(a,-2,4):b},q2=function(a,b){if(!a.X)return null;
try{var c=a.X.get(b)}catch(d){a.X.remove(b)}return c},y2=function(a,b,c){if(a.X)try{a.X.set(b,c)}catch(d){}};
g.eE.prototype.Gi=g.ca(13,function(){for(var a=g.fe(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Ae(a[b])});
g.eW.prototype.Gi=g.ca(12,function(){this.g.Gi()});
g.eE.prototype.gk=g.ca(11,function(){return!!this.g.textTracks});
g.eW.prototype.gk=g.ca(10,function(){return this.g.gk()});
g.eE.prototype.yi=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.eW.prototype.yi=g.ca(8,function(a){this.g.yi(a)});
g.UC.prototype.Yg=g.ca(7,function(){});
g.eE.prototype.Yg=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.eW.prototype.Yg=g.ca(5,function(){return this.g.Yg()});
g.Iz.prototype.bq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Qt.prototype.nl=g.ca(2,function(a){return(a=this.Nf(a))?a.i:0});
g.Jw.prototype.nl=g.ca(1,function(){return 0});
var Sna=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Ana=/#(.)(.)(.)/,zna=/^#(?:[0-9a-f]{3}){1,2}$/i,X1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(h1,g.F);h1.prototype.ty=function(){return!1};
h1.prototype.T=function(){this.kg();g.F.prototype.T.call(this)};
g.r(i1,h1);i1.prototype.Rp=function(a,b,c){b=this.Zi(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.kg();this.g=g.gr(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
i1.prototype.Sp=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())g1(this.i,c.value);a()};
i1.prototype.Zi=function(a,b){var c=a.Hb(),d={fmt:b};a.g&&(d.tlang=d1(a));return g.Yq(c,d)};
i1.prototype.kg=function(){this.g&&this.g.abort()};
j1.prototype.contains=function(a){a=g.wb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
j1.prototype.length=function(){return this.Ua.length/2};
g.r(k1,g.F);g.h=k1.prototype;g.h.T=function(){g.F.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.ww=function(a){var b=this;if(this.D.Gg())var c=this.u.J(this.o,"progresssync",function(){b.D.index.Mb()&&(b.reset(),b.g=null,l1(b,b.o.getCurrentTime()),b.u.La(c))});
else l1(this,a)};
g.h.yE=function(){l1(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new j1;this.i&&(this.i.cancel(),this.i=null)};
g.h.Kv=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.qf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.Hh(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||m1(this,a),this.g=g.Za(a.g)));this.H.start()};
g.h.hJ=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Qw(a);c?(a=g.Zv(this.l,this.N,{}),b=this.l,g.Uv(b.i,a,c),b.requestId=a.get("req_id"),m1(this,this.l)):(b||null===this.F||(this.C?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.qc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.qc()))),this.i=this.l=null)};
g.r(n1,h1);g.h=n1.prototype;g.h.Rp=function(a,b,c){this.kg();b=Cna(this,a.getId());b||(b=a.i,b=this.g.i?p1(this,b,"386"):p1(this,b));if(b){var d=1E3*(b.index.nl(b.index.ce())-b.index.Yc(b.index.ce()));this.l=new k1(new g.ov,this.C,b,function(b,f){c(b,a,f,d)},this.A||g.hv(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.ty=function(){var a=this.o;this.o=!1;return a};
g.h.Sp=function(a){var b;this.A?b=[new g.Iz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Iz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?o1(this,"386"):o1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g1(this.i,c.value);a()};
g.h.kg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Zi=function(){return""};
g.r(q1,h1);q1.prototype.Rp=function(a,b,c){b=this.Zi(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.kg();this.g=g.gr(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q1.prototype.Sp=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Yq(b,c);c=(0,g.y)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.q(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var k=d.value;d=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),u="true"==k.getAttribute("lang_default"),x="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
g1(this.i,new g.Iz({languageCode:d,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:x,vss_id:k,is_default:u}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)l=b[d].getAttribute("lang_code"),m=b[d].getAttribute("lang_translated"),n=b[d].getAttribute("lang_original"),p=b[d].getAttribute("id"),u="true"==b[d].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:u},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.kg();this.g=g.gr(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
q1.prototype.Zi=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.u,kind:a.o,fmt:b};a.g&&(d.tlang=d1(a));return c=g.Yq(c,d)};
q1.prototype.kg=function(){this.g&&this.g.abort()};var Dna=["left","right","center","justify"];var A2={windowColor:"#080808",windowOpacity:0,textAlign:2,Af:7,Ce:50,jg:100,tb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(r1,g.TD);r1.prototype.toString=function(){return g.TD.prototype.toString.call(this)};g.r(s1,g.TD);s1.prototype.toString=function(){return g.TD.prototype.toString.call(this)};
var t1=0;g.r(w1,g.T);g.h=w1.prototype;g.h.xE=function(a,b){var c=g.Di(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.wE=function(a,b){var c=g.Gi(this.element),d=a-this.na-.02*this.Sa,e=b-this.sa-.02*this.Qa,f=(d+c.width/2)/this.ea*3;f=Math.floor(g.Sd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.Sd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ea;d=100*g.Sd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.Sd(c,0,1);this.l.params.Af=l;this.l.params.jg=c;this.l.params.Ce=d;this.i.Af=l;this.i.jg=c;this.i.Ce=d;this.Oy()};
g.h.vE=function(){g.Io(this.element,"ytp-dragging")};
g.h.Oy=function(){this.Vg(this.o)};
g.h.Vg=function(a){var b=Math.min(this.Mu(),this.ea),c=this.Lu(),d="";3==this.l.params.hg&&(d="rotate(180deg)");g.ni(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Vn(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Ce+2;d=this.i.Af;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.u.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.jg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ni(this.element,a)};
g.h.Vn=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.X||this.o.length>b)b=0,this.X=!1,this.o=[],this.D=[],this.K=[],this.H=this.A=null,g.ye(this.u);for(;b<a.length;b++)y1(this,a[b])};
g.h.Mu=function(){return 0};
g.h.Lu=function(){return 0};
g.h.vo=function(a){this.A=g.ve("SPAN");this.A.appendChild(g.we("\u00a0"));this.H=g.ve("SPAN");g.J(this.H,"caption-visual-line");this.A.appendChild(this.H);this.A.appendChild(g.we("\u00a0"));a.appendChild(this.A)};
g.h.toString=function(){return g.T.prototype.toString.call(this)};z1.prototype.u=function(){};B1.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
B1.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var C1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];E1.prototype.set=function(a){this.g=a};
E1.prototype.get=function(){return this.g};
F1.prototype.clear=function(){this.g=0};
F1.prototype.update=function(){this.g=2==this.g?1:0};
F1.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
G1.prototype.If=function(a){this.Dd=a.Dd;this.timestamp=a.timestamp};
G1.prototype.reset=function(){this.timestamp=this.Dd=0};
H1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Dd?a+"_":a+String.fromCharCode(d.Dd)}a+="\n"}return a};
H1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Hna=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ina=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Jna=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Kna=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];O1.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
A1.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.r(S1,g.F);S1.prototype.reset=function(){};g.r(T1,S1);T1.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
T1.prototype.l=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.o,l={},m=c.getAttribute("p");m&&g.Wa(l,this.o[m]);m=V1(c,"b");null!=m&&(l.bold=
m);m=V1(c,"i");null!=m&&(l.Ae=m);m=V1(c,"u");null!=m&&(l.underline=m);m=W1(c,"et");null!=m&&(l.charEdgeStyle=m);m=W1(c,"of");null!=m&&(l.offset=m);m=Y1(c,"bc");null!=m&&(l.background=m);m=Y1(c,"ec");null!=m&&(l.Lt=m);m=Y1(c,"fc");null!=m&&(l.color=m);m=W1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=U1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=U1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=U1(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=W1(c,"rb");null!=c&&(l.NK=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.H[d]=Z1(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=$1(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=a2(this,d,e,!1);g.H(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.u;m=!!V1(d,"a");n=(U1(d,"t")||0)+n;var p=U1(d,"d")||5E3;m||(!this.C&&
this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var u=m?6:5,x=this.o[d.getAttribute("p")],B=d.childNodes;B.length&&(this.C=null!=d.getAttribute("d"));for(var E=0;E<B.length;E++){var G=B[E];0<E&&(m=!0);var S=void 0;1==G.nodeType&&(S=G);if(S&&"s"==S.tagName)if((G=this.o[S.getAttribute("p")])&&1==G.NK&&!g.P(this.N.experiments,"web_player_vertical_and_ruby_captions_killswitch")){G=n;var V=p,ra=l,vb=m,Eb=u;var Mc=S;var Zf=B[E+1],Dh=B[E+2],Cc=B[E+3];
Mc.getAttribute("p");U1(Mc,"t");U1(Zf,"t");U1(Dh,"t");U1(Cc,"t");S=g.ve("RUBY");Mc=Mc.textContent;var Hk=g.ve("SPAN");Hk.innerText=Mc;S.appendChild(Hk);Zf.getAttribute("p");Hk=g.ve("RP");Mc=Zf.textContent;Hk.innerText=Mc;S.appendChild(Hk);Dh.getAttribute("p");Mc=Dh.textContent;Zf=g.ve("RT");Zf.innerText=Mc;S.appendChild(Zf);Cc.getAttribute("p");Mc=Cc.textContent;Cc=g.ve("RP");Cc.innerText=Mc;S.appendChild(Cc);G=new r1(G,V,Eb,ra,S,vb,null);E+=3}else Cc=S,G=n,V=p,ra=l,vb=m,Eb=u,S=Cc.textContent?Cc.textContent:
"",Mc=this.o[Cc.getAttribute("p")],Cc=U1(Cc,"t")||0,G=new r1(G+Cc,V-Cc,Eb,ra,S,vb,Mc);else G=new r1(n,p,u,l,G.textContent||"",m,x);k.push(G);this.i=G}if(0<k.length)for(k[0].windowId==this.u&&(this.g=a2(this,d,e,!0),g.H(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.H(l,k),l.i.push(k),c.push(k)}e=c}else e=[];return e};g.r(b2,w1);b2.prototype.Vn=function(a){var b=this.l.i;w1.prototype.Vn.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Wa(d,c.i);g.Wa(d,Tna);var e=c.i;var f=d}y1(this,c,d)}};
var Tna={sl:!0};g.r(c2,z1);c2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+t1++;c=c/1E3-this.C;d=d/1E3-this.C;a=new s1(c,d-c,5,f,{textAlign:0,Af:0,Ce:2.5*b,jg:5.33*a});e=new r1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(f2,S1);f2.prototype.l=function(a){a=new c2(a,a.byteLength,this.i);if(g2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=e2(a)*(1E3/45):1==a.version&&(a.o=4294967296*e2(a)+e2(a)),a.A=d2(a);0<a.A;a.A--){var b=d2(a),c=d2(a),d=d2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Ft:c,Gt:d,order:b.g.length}))}Gna(this.g,a);return a.l}return[]};
f2.prototype.reset=function(){this.g.clear()};g.r(i2,w1);g.h=i2.prototype;g.h.Oy=function(){g.So(this.ia)};
g.h.mJ=function(){g.Io(this.element,"ytp-rollup-mode");this.Vg(this.Ca,!0)};
g.h.Lu=function(){return this.C?this.R:this.O};
g.h.Mu=function(){return this.C?this.O:this.R};
g.h.vo=function(a){w1.prototype.vo.call(this,a);g.J(this.A,"ytp-rollup-caption-line-wrapper");g.ni(this.A,"display","inline-block");g.ni(this.H,"display","inline-block")};
g.h.Vg=function(a,b){this.Ca=a;if(this.l.params.rr){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));this.xa=this.R;this.O=this.R=0;w1.prototype.Vg.call(this,a);Pna(this,b);w1.prototype.Vg.call(this,a)}else w1.prototype.Vg.call(this,a)};g.r(k2,S1);
k2.prototype.l=function(a,b){for(var c=[],d=a.split(Una),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Vna.test(f)){var l=F2.exec(f);if(l&&4<=l.length){var m=m2(l[1]),n=m2(l[2])-m;m+=k;var p,u=p=void 0,x=void 0,B=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var G=E.next();!G.done;G=E.next())if(G=G.value.split(":"),2==G.length){var S=G[1];switch(G[0]){case "line":G=S.split(",");G[0].endsWith("%")&&(B=G[0],l.jg=Number.parseInt(B,10),2==G.length&&(x=G[1].trim()));break;case "position":G=S.split(",");
u=G[0];l.Ce=Number.parseInt(u,10);2==G.length&&(p=G[1].trim());break;case "align":switch(S){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}B||(l.jg=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.Ce=0;break;case 1:l.Ce=100;break;default:l.Ce=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(p){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.Af=0>u||8<u?7:u;p=l;f=f.substring(F2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=n2(m,n,5,u),n=new r1(m,n,5,k.id,p,!1,g.jc(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.i.push(n);else for(x=p.split(Wna),1==x.length?(p=5,u=n2(m,n,p,u)):(B=p=6,u=Object.assign({Qt:32},u),u=new s1(m,n,B,"_"+t1++,u)),c.push(u),B=m,l=0;l<x.length;l++)E=x[l],0==l%2?(G=g.Ko("<html>"+E+"</html>"),G.getElementsByTagName("parsererror").length?
(S=G.createElement("span"),S.appendChild(G.createTextNode(E))):S=G.firstChild,l2(this,B,n-(B-m),p,u,0<l,S,f,c)):B=m2(E)+k}F2.lastIndex=0}}return c};
var Vna=/^NOTE/,Una=/(?:\r\n|\r|\n){2,}/,F2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Wna=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(o2,g.F);o2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
o2.prototype.reset=function(){this.g&&this.g.reset()};
o2.prototype.T=function(){this.clear();g.F.prototype.T.call(this)};g.r(r2,g.rK);g.h=r2.prototype;g.h.T=function(){if(this.C||this.P){var a=this.N.app.u;a&&a.Gi()}else C2(this,!1);g.rK.prototype.T.call(this)};
g.h.ak=function(){return this.la?this.C||this.P:t2(this)?!0:s2(this)};
g.h.load=function(){g.rK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.W.clear(),this.C?x2(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Rp(this.g,"srv3",(0,g.y)(this.QJ,this))),this.g&&!w2(this)?this.player.ma("captionschanged",c1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new n1(this.o.ka,this.player):this.xa?a=new i1(this.l,this.o,this.player.getAudioTrack()):a=new q1(this.o.Ei,this.o.videoId,this.o.Df||this.l.Df||
g.LB(this.o,"yt:cc_default_lang")||this.l.Jb,this.o.fo,this.l);this.i=a;g.H(this,this.i);a.Sp((0,g.y)(this.PJ,this))}};
g.h.unload=function(){this.C&&this.g?x2(this,!1):(this.ba&&g.To(this.ba),g.bK(this.player,"captions"),this.H=[],this.i&&this.i.kg(),this.W.clear(),this.F&&g.ZJ(this.player,this.F),this.Ur());g.rK.prototype.unload.call(this);var a=g.X(this.player.app);a&&a.o&&g.IC(a.o.l);this.player.ma("captionschanged",{})};
g.h.PJ=function(){var a;this.K||s2(this)?a=v2(this,this.K):t2(this)&&(a=u2(this));if(this.C||this.P){for(var b=f1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Jz(e),srclang:d1(e),id:e.toString()};this.P||(f.src=this.i.Zi(e,"vtt"));e==a&&(f["default"]=1);c.push(g.te("TRACK",f))}this.N.app.u.yi(c);a=this.N.app.u.ha();this.sa&&this.aa.J(a.textTracks,"change",this.RJ)}else!this.g&&a&&z2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.RJ=function(){for(var a=this.N.app.u.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=f1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&z2(this,b,!0)};
g.h.nL=function(){!this.g&&this.C||this.unload()};
g.h.QJ=function(a,b,c,d){if(a){this.i.ty()&&(this.H=[],g.bK(this.N,"captions"),this.ga.dj(),this.W.reset());var e=this.W;c=c||0;d=d||0;if(!g.t(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.ku(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!h2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],u=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|u&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.t(a)){if("WEBVTT"==a.substring(0,6)){b=a;var x=c;e.g||(e.g=new k2);var B=e.g.l(b,x);.01>Math.random()&&g.nq(Error("Deprecated subtitles format in web player: WebVTT"));var E=B}else b:{B=a;x=g.Ko(B);if(!x||!x.firstChild)throw Error("Invalid caption track data: "+
B);if("timedtext"==x.firstChild.tagName){if(3==parseInt(x.firstChild.getAttribute("format"),10)){if(!e.g){B={};var G=d1(b);G&&(B.lang=G,Sna.test(G)&&(B.hg=1));e.g=new T1(B,e.i)}E=e.g.l(x,c);break b}var S=Error("Unsupported subtitles format in web player (Format2)");S.params=B;throw S;}if("transcript"==x.firstChild.tagName)throw Error("Unsupported subtitles format in web player (Format1): "+B);throw Error("Invalid caption track data: "+B);}var V=E}else{E=a;x=c;G=d;if(!h2(E))throw Error("Invalid binary caption track data");
e.g||(e.g=new f2(G,b));V=e.g.l(E,x)}var ra=V}catch(vb){g.M(vb),e.clear(),ra=[]}else ra=[];g.ZJ(this.player,ra);!this.K||this.P||w2(this)||g.jz(this.l)||g.kz(this.l)||(g.To(this.ba),ra=u1({Af:0,Ce:5,jg:5,rr:2,textAlign:0,hg:0,lang:"en"}),this.R=[ra],e=["Click "," for settings"],this.ia||(V=new g.jC(g.oP()),g.H(this,V),this.ia=V.element),V=ra.end-ra.start,(b=g.Jz(this.g))&&this.R.push(new r1(ra.start,V,0,ra.id,b)),this.R.push(new r1(ra.start,V,0,ra.id,e[0]),new r1(ra.start,V,0,ra.id,this.ia,!0),new r1(ra.start,
V,0,ra.id,e[1],!0)),g.ZJ(this.player,this.R),g.Ro(this.ba));!this.K||this.P||w2(this)||(y2(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(ra=g.X(this.player.app))&&ra.o&&g.IC(ra.o.l));this.K=!1}};
g.h.HD=function(a){this.H.push(a);this.ga.dj()};
g.h.ID=function(a){g.jb(this.H,a);this.i instanceof n1&&this.i.A&&g.aK(this.player,[a]);this.ga.dj()};
g.h.CK=function(a){if(a instanceof s1){var b=this.O[a.id];b&&b.l!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=Qna(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.IK=function(){B2(this,this.R);this.R=null};
g.h.Mz=function(){this.ga.stop();g.kc(this.Z);this.H.sort(g.VD);var a=this.H;if(this.F){var b=(0,g.Ce)(a,function(a){return-1==this.F.indexOf(a)},this);
b.length&&(a=b)}(0,g.A)(a,this.CK,this);g.Xb(this.O,function(a,b){this.Z[b]?(a.element.parentNode||g.fK(this.player,a.element,4),a.Vg(this.Z[b])):(a.dispose(),delete this.O[b])},this)};
g.h.MK=function(){p2(this,{},!0)};
g.h.No=function(){var a=A2.tb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ae?3:a.bold?1:a.Ae?2:0,textOpacity:a.textOpacity,windowColor:A2.windowColor,windowOpacity:A2.windowOpacity};var b=q2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.Xr=function(a,b){var c={};g.Wa(c,q2(this,"display-settings"));g.Wa(c,a);p2(this,c,b);this.player.M("captionssettingschanged")};
g.h.Ur=function(){!this.C&&this.loaded&&(g.Xb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.Mz())};
g.h.Wb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Sd(b,-2,4);this.Xr({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&z2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.sb&&y2(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.jc(b)){z2(this,null,!0);break}for(var d=f1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?yna(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||z2(this,c,!0)}else return this.loaded&&this.g&&!w2(this)?c1(this.g):{};return"";case "tracklist":return this.i?(0,g.D)(f1(this.i.i,!(!b||!b.includeAsr)),function(a){return c1(a)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "displaySettings":c=this.No();if(this.Ca&&g.jz(this.l)&&b&&g.Pa(b)){d={};null!=b.color&&(d.color=D2(b.color,c.color),d.colorOverride=!0);null!=b.background&&(d.background=D2(b.background,c.background),d.backgroundOverride=!0);null!=b.windowColor&&(d.windowColor=D2(b.windowColor,c.windowColor),d.windowColorOverride=!0);null!=b.textOpacity&&(d.textOpacity=E2(b.textOpacity,c.textOpacity),d.textOpacityOverride=!0);null!=b.backgroundOpacity&&(d.backgroundOpacity=
E2(b.backgroundOpacity,c.backgroundOpacity),d.backgroundOpacityOverride=!0);null!=b.windowOpacity&&(d.windowOpacity=E2(b.windowOpacity,c.windowOpacity),d.windowOpacityOverride=!0);null!=b.charEdgeStyle&&(e=g.IY[b.charEdgeStyle],d.charEdgeStyle=g.Ha(e)?e:c.charEdgeStyle,d.charEdgeStyleOverride=!0);null!=b.fontSizeIncrement&&(d.fontSizeIncrement=Rna(b.fontSizeIncrement,c.fontSizeIncrement),d.fontSizeIncrementOverride=!0);e=b.fontFamilyOption;if(null!=b.fontFamily||null!=e)e=g.HY[null!=b.fontFamily?
b.fontFamily:e],d.fontFamily=g.Ha(e)?e:c.fontFamily,d.fontFamilyOverride=!0;null!=b.fontStyle&&(e=g.JY[b.fontStyle],d.fontStyle=g.Ha(e)?e:c.fontStyle,d.fontStyleOverride=!0);this.Xr(d,!0);c=this.No()}if(this.Aa)return d=c,d.fontFamilyOption=g.Dla[c.fontFamily],d.charEdgeStyle=g.Ela[c.charEdgeStyle],d.fontStyle=g.Fla[c.fontStyle],d;case "sampleSubtitles":this.C||void 0==b||C2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.l.sb&&a.push("stickyLoading");return a};
g.h.bj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.Dz=function(){this.loaded&&this.g&&!w2(this)?(y2(this,"module-enabled",!1),this.unload(),t2(this,!0)&&z2(this,u2(this),!1)):z2(this,w2(this)||!this.g?v2(this,!0):this.g,!0)};
g.h.FG=function(){var a=w2(this);t2(this,a)?z2(this,this.player.getAudioTrack().Zk,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.ak()&&(a?z2(this,v2(this),!1):this.load()))};g.vU.captions=r2;})(_yt_player);
