(function(g){var window=this;var G2=function(a,b,c){var d=b.ua();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.oc(c?c:"mqdefault.jpg");var f=b instanceof g.lB&&b.lengthSeconds?g.QP(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.XD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.lB?b.oa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.zi||g.LN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.cj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.ZD&&(d.playlist_length=b.getLength());a.update(d)},H2=function(a,b){g.oC.call(this,{B:"div",
V:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},I2=function(a){g.T.call(this,{B:"div",
V:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},I:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",I:[{B:"span",G:"ytp-upnext-header",U:"Up Next"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},I:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},I:[{B:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",I:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.u=null;var b=this.g["ytp-upnext-cancel"];this.u=new g.T({B:"button",V:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.H(this,this.u);this.u.ca("click",this.KG,this);this.u.Y(b);this.i=a;this.H=this.g["ytp-svg-autoplay-ring"];this.C=this.A=this.l=this.o=null;this.D=new g.L(this.Pk,5E3,this);g.H(this,this.D);this.F=0;this.J(this.g["ytp-upnext-autoplay-icon"],"click",this.CI);this.vx();this.J(a,"autonavvisibility",this.vx);this.J(a,"mdxnowautoplaying",
this.RH);this.J(a,"mdxautoplaycanceled",this.SH);this.J(a,"mdxautoplayupnext",this.Qz);3==this.i.getPresentingPlayerType()&&(a=(a=g.RJ(g.LJ(this.i)))?a.NB():null)&&this.Qz(a)},J2=function(a,b){if(!a.l){g.Cq("a11y-announce","Up Next "+a.o.title);
a.F=g.O();a.l=new g.L((0,g.y)(a.Un,a,b),25);a.Un(b);var c=b||g.Q(g.W(a.i).experiments,"autoplay_time")||1E4;a.i.ma("onAutonavCoundownStarted",c)}g.Io(a.element,"ytp-upnext-autoplay-paused")},L2=function(a){K2(a);
a.F=g.O();a.Un();g.J(a.element,"ytp-upnext-autoplay-paused")},K2=function(a){a.l&&(a.l.dispose(),a.l=null)},M2=function(a,b){b=void 0===b?!1:b;
if(g.P(g.W(a.i).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.o.ua(),a.Pk(),a.A=new Notification("Up Next",{body:c.title,icon:c.oc()}),a.C=a.J(a.A,"click",a.uI),a.D.start())}K2(a);a.i.nextVideo(!1,b)},N2=function(a){H2.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.i=new g.T({B:"div",G:"ytp-subscribe-card",I:[{B:"img",G:"ytp-author-image",L:{src:b.Wd}},{B:"div",G:"ytp-subscribe-card-right",I:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.H(this,this.i);this.i.Y(this.element);this.l=new g.pV("Subscribe",null,"Unsubscribe",null,!0,!1,b.ah,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.l);this.l.Y(this.i.g["html5-subscribe-button-container"]);this.hide()},O2=function(a){var b=
g.W(a),c=g.mx||g.qi?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.T.call(this,{B:"a",V:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},I:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",I:[{B:"span",G:"ytp-videowall-still-info-bg",I:[{B:"span",G:"ytp-videowall-still-info-content",L:c,I:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"Live"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",V:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],I:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",I:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",V:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],I:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.u=d;this.i=a;this.l=null;this.o=new g.us(this);g.H(this,this.o);this.ca("click",this.C);this.ca("keypress",this.D);this.o.J(a,"videodatachange",this.A);g.W(a).F&&g.$K(a.app.R,this.element,this);this.A()},P2=function(a){g.iK(a.i,a.element);
var b=a.l.ua().videoId,c=a.l.getPlaylistId();g.uX(a.i.app,b,a.l.Qc,c,void 0,void 0,void 0)},Q2=function(a){H2.call(this,a,"videowall-endscreen");
this.F=a;this.A=0;this.l=[];this.C=this.o=this.u=null;this.D=this.R=!1;this.O=null;this.aa=new g.us(this);g.H(this,this.aa);this.H=new g.L(g.Va(g.J,this.element,"ytp-show-tiles"),0);g.H(this,this.H);var b=new g.T({B:"button",V:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},I:[g.VO()]});g.H(this,b);b.Y(this.element);b.ca("click",this.lE,this);this.K=new g.jC({B:"div",G:"ytp-endscreen-content"});g.H(this,this.K);this.K.Y(this.element);b=new g.T({B:"button",V:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},I:[g.WO()]});g.H(this,b);b.Y(this.element);b.ca("click",this.kE,this);this.i=new I2(a);g.H(this,this.i);g.fK(this.player,this.i.element,4);this.hide()},R2=function(a){return g.gK(a.player)&&a.zt()&&!a.C},S2=function(a,b){return(0,g.D)(b.suggestions,function(b){b=g.wR(g.W(a.F),b);
g.H(a,b);return b})},T2=function(a){var b=a.ye();
b!=a.R&&(a.R=b,a.player.M("autonavvisibility"))},V2=function(a){g.rK.call(this,a);
this.g=null;this.i=new g.us(this);g.H(this,this.i);this.l=g.W(a);U2(a)?this.g=new Q2(this.player):this.l.Ra?this.g=new N2(this.player):this.g=new H2(this.player);g.H(this,this.g);g.fK(this.player,this.g.element,4);this.Ny();this.i.J(a,"videodatachange",this.Ny,this);this.i.J(a,g.WD("endscreen"),this.BD,this);this.i.J(a,"crx_endscreen",this.CD,this)},U2=function(a){a=g.W(a);
return a.Fa&&!a.Ra};
g.r(H2,g.oC);H2.prototype.create=function(){this.created=!0};
H2.prototype.destroy=function(){this.created=!1};
H2.prototype.zt=function(){return!1};
H2.prototype.ye=function(){return!1};g.r(I2,g.T);g.h=I2.prototype;g.h.Pk=function(){this.A&&(this.D.stop(),this.La(this.C),this.C=null,this.A.close(),this.A=null)};
g.h.vx=function(){g.nC(this,this.i.ye())};
g.h.uI=function(){window.focus();this.Pk()};
g.h.hide=function(){g.T.prototype.hide.call(this)};
g.h.Un=function(a){a=a||g.Q(g.W(this.i).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.F,a);a=Math.min(b/a,1);this.H.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.i.getPresentingPlayerType()?M2(this,!0):this.l&&this.l.start()};
g.h.CI=function(a){!g.He(this.u.element,g.hs(a))&&g.zR(a,this.i)&&M2(this)};
g.h.KG=function(){g.NJ(this.i,!0)};
g.h.RH=function(a){this.i.getPresentingPlayerType();this.show();J2(this,a)};
g.h.Qz=function(a){this.i.getPresentingPlayerType();this.o&&this.o.ua().videoId==a.ua().videoId||(this.o=a,G2(this,a,"hqdefault.jpg"))};
g.h.SH=function(){this.i.getPresentingPlayerType();K2(this);this.hide()};
g.h.T=function(){K2(this);this.Pk();g.T.prototype.T.call(this)};g.r(N2,H2);g.r(O2,g.T);O2.prototype.C=function(a){g.zR(a,this.i,this.u,this.l.Qc||void 0)&&P2(this)};
O2.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.ns(a)||(P2(this),g.ms(a))}};
O2.prototype.A=function(){var a=this.i.getVideoData(),b=g.W(this.i);this.u=a.Yb?!1:b.i};g.r(Q2,H2);g.h=Q2.prototype;g.h.create=function(){H2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=S2(this,a),this.o=a);this.sf();this.aa.J(this.player,"appresize",this.sf);this.aa.J(this.player,"onVideoAreaChange",this.sf);this.aa.J(this.player,"videodatachange",this.mE);this.aa.J(this.player,"autonavchange",this.iq);this.aa.J(this.player,"autonavcancel",this.jE);a=this.o.autonavState;a!=this.O&&this.iq(a);this.aa.J(this.element,"transitionend",this.SJ)};
g.h.destroy=function(){g.ws(this.aa);g.Yf(this.l);this.l=[];this.u=null;H2.prototype.destroy.call(this);g.Io(this.element,"ytp-show-tiles");this.H.stop();this.O=this.o.autonavState};
g.h.zt=function(){return 1!=this.o.autonavState};
g.h.show=function(){H2.prototype.show.call(this);g.Io(this.element,"ytp-show-tiles");g.W(this.player).g?g.So(this.H):this.H.start();(this.D||this.C&&this.C!=this.o.clientPlaybackNonce)&&g.NJ(this.player,!1);R2(this)?(T2(this),2==this.o.autonavState?g.P(g.W(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?M2(this.i,!0):J2(this.i):3==this.o.autonavState&&L2(this.i)):(g.NJ(this.player,!0),T2(this))};
g.h.hide=function(){H2.prototype.hide.call(this);L2(this.i);T2(this)};
g.h.SJ=function(a){g.hs(a)==this.element&&this.sf()};
g.h.sf=function(){if(this.u&&this.u.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.XJ(this.F,!0),b=g.DC(this.F);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,u=e/2,x=b<=f-2&&n>=u*m,B=e<=k-2&&n>=p*m;if((p+1)/u*d/c>c/(p/(u+1)*d)&&B)n-=p*m,e+=2;else if(x)n-=u*m,b+=2;else if(B)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Sd(a.width/m||1,1,1.21);n*=g.Sd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.K.element;g.Fi(a,m,n);g.ni(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.i;f=this.u[0];c.o=f;G2(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",R2(this));T2(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,u=0,d&&f>=b-2&&k>=e-
2?u=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(u=2):u=2),p=g.Td(p+this.A,l),0!=u){x=this.l[c];x||(x=new O2(this.player),this.l[c]=x,a.appendChild(x.element));B=Math.floor(n*k/e);var E=Math.floor(m*f/b),G=Math.floor(n*(k+u)/e)-B-4,S=Math.floor(m*(f+u)/b)-E-4;g.vi(x.element,E,B);g.Fi(x.element,S,G);g.ni(x.element,"transitionDelay",(k+f)/20+"s");g.K(x.element,"ytp-videowall-still-mini",1==u);g.K(x.element,"ytp-videowall-still-large",2<u);u=x;p=this.u[p];u.l!=p&&(u.l=p,G2(u,p,g.Go(u.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Qc)&&p.itct)&&(x=u.i,g.W(x).F&&g.aL(x.app.R,u.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.l.length-1;b>=c;b--)e=this.l[b],g.Ae(e.element),g.Xf(e);this.l.length=c}};
g.h.mE=function(){var a=this.player.getVideoData();this.o!=a&&(this.A=0,this.u=S2(this,a),this.o=a,this.sf())};
g.h.kE=function(){this.A+=this.l.length;this.sf()};
g.h.lE=function(){this.A-=this.l.length;this.sf()};
g.h.MC=function(){return!!this.i.l};
g.h.iq=function(a){1==a?(this.D=!1,this.C=this.o.clientPlaybackNonce,K2(this.i),this.Ea()&&this.sf()):(this.D=!0,this.Ea()&&R2(this)&&(2==a?J2(this.i):3==a&&L2(this.i)))};
g.h.jE=function(a){if(a){for(a=0;a<this.l.length;a++)g.jK(this.F,this.l[a].element,!0);this.iq(1)}else this.C=null,this.D=!1;this.sf()};
g.h.ye=function(){return this.Ea()&&R2(this)};g.r(V2,g.rK);g.h=V2.prototype;g.h.ak=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!U2(this.player)||b;a=!!a.rd.ypc_module;var c=g.VW(this.player.app);return b&&!a&&!c};
g.h.ye=function(){return this.g.ye()};
g.h.IC=function(){return this.ye()?this.g.MC():!1};
g.h.T=function(){g.bK(this.player,"endscreen");g.rK.prototype.T.call(this)};
g.h.load=function(){g.rK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.rK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.BD=function(a){this.ak()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.CD=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Ny=function(){g.bK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.TD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.TD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.ZJ(this.player,[a,b])};g.vU.endscreen=V2;})(_yt_player);
