(function(g){var window=this;var doa=function(a,b){return g.gc(a,b)},a4=function(){},eoa=function(a){if(a.sc&&"function"==typeof a.sc)return a.sc();
if(g.t(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.cc(a)},foa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.t(a))(0,g.A)(a,b,void 0);else{if(a.wd&&"function"==typeof a.wd)var c=a.wd();else if(a.sc&&"function"==typeof a.sc)c=void 0;else if(g.Na(a)||g.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.dc(a);d=eoa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},b4=function(a){g.Jn(a,"zx",g.Ec());
return a},c4=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.On(a.l,b,c)},d4=function(a){return(a=g.ep(a))?new ActiveXObject(a):new XMLHttpRequest},e4=function(a,b){return b+" ["+a.X+" "+a.F+" "+a.getStatus()+"]"},goa=function(a){return"content-type"==a.toLowerCase()},f4=function(a){a.g&&a.N&&(a.g.ontimeout=null);
a.C&&(g.v.clearTimeout(a.C),a.C=null)},hoa=function(a){return g.ne&&g.Tc(9)&&g.Ha(a.timeout)&&g.Fa(a.ontimeout)},g4=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},h4=function(a,b){if(a.g){f4(a);
var c=a.g,d=a.K[0]?g.Ja:null;a.g=null;a.K=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},i4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;g4(a);h4(a)},j4=function(a){return a.g?a.g.readyState:0},k4=function(a){if(a.i&&"undefined"!=typeof g.KX)if(a.K[1]&&4==j4(a)&&2==a.getStatus())e4(a,"Local request error detected and ignored");
else if(a.D&&4==j4(a))g.th(a.bv,0,a);else if(a.dispatchEvent("readystatechange"),4==j4(a)){e4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Fh(String(a.F))[1]||null;if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!ioa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<j4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";g4(a)}}finally{h4(a)}}},l4=function(a){g.Cg.call(this);
this.headers=new g.yn;this.O=a||null;this.i=!1;this.K=this.g=null;this.X=this.F="";this.u=0;this.l="";this.o=this.Z=this.D=this.R=!1;this.A=0;this.C=null;this.W="";this.N=this.P=!1},m4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},joa=function(a,b){var c=[];
g.wl(b,function(a){try{var b=g.tp.prototype.i.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Fa(b)?g.sp(b)&&c.push(a):c.push(a)},a);
return c},koa=function(a,b){var c=joa(a,b);
(0,g.A)(c,function(a){g.tp.prototype.remove.call(this,a)},a)},n4=function(a){if(a.Rc){if(a.Rc.locationOverrideToken)return{locationOverrideToken:a.Rc.locationOverrideToken};
if(null!=a.Rc.latitudeE7&&null!=a.Rc.longitudeE7)return{latitudeE7:a.Rc.latitudeE7,longitudeE7:a.Rc.longitudeE7}}return null},loa=function(a,b){g.fb(a,b)||a.push(b)},o4=function(a){var b=0,c;
for(c in a)b++;return b},moa=function(a,b,c,d){var e=new g.Bn(null,void 0);
a&&g.Cn(e,a);b&&g.Dn(e,b);c&&g.En(e,c);d&&(e.i=d);return e},p4=function(){this.g=[];
this.i=[]},q4=function(a,b){g.xq[a]=!0;
var c=g.vq();c&&c.publish.apply(c,arguments);g.xq[a]=!1},r4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.yn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",noa(this,a.capabilities||""),ooa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},noa=function(a,b){a.capabilities.clear();
(0,g.Ce)(b.split(","),g.Va(doa,poa)).forEach(function(b){a.capabilities.add(b)})},ooa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},s4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},t4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},u4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},qoa=function(a){return new s4(a)},v4=function(a){return g.Ma(a)?(0,g.D)(a,qoa):[]},w4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},x4=function(a){return g.Ma(a)?"["+(0,g.D)(a,w4).join(",")+"]":"null"},y4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},roa=function(a){return(0,g.D)(a,function(a){return{key:a.id,
name:a.name}})},z4=function(a,b){return g.bb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},A4=function(a,b){return g.bb(a,function(a){return t4(a,b)})},soa=function(){var a=(0,g.It)();
a&&koa(a,a.g.Te(!0))},B4=function(){var a=g.Lt("yt-remote-connected-devices")||[];
g.yb(a);return a},toa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.D)(a,function(a,b){return 0==b?a:a.substring(c.length)})},C4=function(a){g.Kt("yt-remote-connected-devices",a,86400)},E4=function(){if(D4)return D4;
var a=g.Lt("yt-remote-device-id");a||(a=y4(),g.Kt("yt-remote-device-id",a,31536E3));for(var b=B4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return D4=d},F4=function(){var a=B4(),b=E4();
g.fb(a,b);g.Nt()&&g.Cb(a,b);a=toa(a);if(0==a.length)try{g.ft("remote_sid")}catch(c){}else try{g.et("remote_sid",a.join(","),-1)}catch(c){}},G4=function(){return g.Lt("yt-remote-session-browser-channel")},H4=function(){return g.Lt("yt-remote-local-screens")||[]},I4=function(){g.Kt("yt-remote-lounge-token-expiration",!0,86400)},uoa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.D)(H4(),function(a){return a.loungeToken}),c=(0,g.D)(a,function(a){return a.loungeToken});
(0,g.kn)(c,function(a){return!g.fb(b,a)})&&I4();
g.Kt("yt-remote-local-screens",a,31536E3)},voa=function(a,b){g.Kt("yt-remote-session-browser-channel",a);
g.Kt("yt-remote-session-screen-id",b);var c=B4(),d=E4();g.fb(c,d)||c.push(d);C4(c);F4()},J4=function(a){a||(g.Mt("yt-remote-session-screen-id"),g.Mt("yt-remote-session-video-id"));
F4();a=B4();g.jb(a,E4());C4(a)},L4=function(){if(!K4){var a=g.Dp();
a&&(K4=new g.np(a))}return K4?!!K4.get("yt-remote-use-staging-server"):!1},M4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},N4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},P4=function(a){a.length?O4(a.shift(),function(){P4(a)}):Q4()},woa=function(a){return"chrome-extension://"+a+R4},O4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Q4=function(){var a=N4();
a&&a(!1,"No cast extension found")},S4=function(){if(xoa){var a=2,b=N4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;O4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Q4,c)}},yoa=function(){S4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);P4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+R4,"//www.gstatic.com/eureka/clank"+R4])},T4=function(a,b,c){g.F.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Lc=b;this.u=(0,g.y)(this.RB,this);this.g=!1;this.i=0;this.l=this.Ba=null;this.o=[]},U4=function(){},V4=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.Pn(this);this.i=new g.sh;this.i.setInterval(250)},X4=function(a,b,c){a.sh=1;
a.Rf=b4(b.clone());a.Qg=c;a.u=!0;W4(a,null)},Y4=function(a,b,c,d,e){a.sh=1;
a.Rf=b4(b.clone());a.Qg=null;a.u=c;e&&(a.Ty=!1);W4(a,d)},W4=function(a,b){a.Vh=(0,g.C)();
Z4(a);a.gg=a.Rf.clone();c4(a.gg,"t",a.A);a.lk=0;a.hc=a.g.wo(a.g.ck()?b:null);0<a.Xo&&(a.Gm=new g.em((0,g.y)(a.Zz,a,a.hc),a.Xo));a.aa.ca(a.hc,"readystatechange",a.EK);var c=a.yg?g.oc(a.yg):{};a.Qg?(a.un="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.hc.send(a.gg,a.un,a.Qg,c)):(a.un="GET",a.Ty&&!g.pe&&(c.Connection="close"),a.hc.send(a.gg,a.un,null,c));a.g.fe(1)},f5=function(a,b,c){for(var d=!0;!a.qg&&a.lk<c.length;){var e=zoa(a,c);
if(e==$4){4==b&&(a.Sf=4,a5(15),d=!1);break}else if(e==b5){a.Sf=4;a5(16);d=!1;break}else c5(a,e)}4==b&&0==c.length&&(a.Sf=1,a5(17),d=!1);a.ke=a.ke&&d;d||(d5(a),e5(a))},zoa=function(a,b){var c=a.lk,d=b.indexOf("\n",c);
if(-1==d)return $4;c=Number(b.substring(c,d));if(isNaN(c))return b5;d+=1;if(d+c>b.length)return $4;var e=b.substr(d,c);a.lk=d+c;return e},i5=function(a,b){a.Vh=(0,g.C)();
Z4(a);var c=b?window.location.hostname:"";a.gg=a.Rf.clone();g.Jn(a.gg,"DOMAIN",c);g.Jn(a.gg,"t",a.A);try{a.me=new ActiveXObject("htmlfile")}catch(n){d5(a);a.Sf=7;a5(22);e5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in g5)k=g5[l];else if(l in h5)k=g5[l]=h5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
g5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rd(g.ed("b/12014412"),d+"</body></html>");a.me.open();a.me.write(g.Hd(c));a.me.close();a.me.parentWindow.m=(0,g.y)(a.VJ,a);a.me.parentWindow.d=(0,g.y)(a.ay,a,!0);a.me.parentWindow.rpcClose=(0,g.y)(a.ay,a,!1);c=a.me.createElement("DIV");a.me.parentWindow.document.body.appendChild(c);d=g.sd(a.gg.toString());d=g.yc(g.pd(d));d=g.Rd(g.ed("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Md(c,g.Hd(d));a.g.fe(1)},Z4=function(a){a.gs=(0,g.C)()+
a.o;
j5(a,a.o)},j5=function(a,b){if(null!=a.ji)throw Error("WatchDog timer not null");
a.ji=k5((0,g.y)(a.fK,a),b)},l5=function(a){a.ji&&(g.v.clearTimeout(a.ji),a.ji=null)},e5=function(a){a.g.Zu()||a.qg||a.g.qm(a)},d5=function(a){l5(a);
g.Xf(a.Gm);a.Gm=null;a.i.stop();g.Rn(a.aa);if(a.hc){var b=a.hc;a.hc=null;b.abort();b.dispose()}a.me&&(a.me=null)},c5=function(a,b){try{a.g.Ux(a,b),a.g.fe(4)}catch(c){}},n5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;m5(a,b,function(e){e?c(!0):g.v.setTimeout(function(){n5(a,b,c,d,f)},f)})}},m5=function(a,b,c){var d=new Image;
d.onload=function(){try{o5(d),c(!0)}catch(e){}};
d.onerror=function(){try{o5(d),c(!1)}catch(e){}};
d.onabort=function(){try{o5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},o5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},p5=function(a){this.g=a;
this.i=new U4},r5=function(a){var b=q5(a.g,a.Bi,"/mail/images/cleardot.gif");
b4(b);n5(b.toString(),5E3,(0,g.y)(a.kB,a),3,2E3);a.fe(1)},t5=function(a){var b=a.g.F;
if(null!=b)a5(5),b?(a5(11),s5(a.g,a,!1)):(a5(12),s5(a.g,a,!0));else if(a.Cd=new V4(a,void 0,void 0,void 0),a.Cd.yg=a.Vo,b=a.g,b=q5(b,b.ck()?a.hj:null,a.Wo),a5(5),!g.ne||g.Vc(10))c4(b,"TYPE","xmlhttp"),Y4(a.Cd,b,!1,a.hj,!1);else{c4(b,"TYPE","html");var c=a.Cd;a=!!a.hj;c.sh=3;c.Rf=b4(b.clone());i5(c,a)}},u5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new U4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Aoa=function(a,b){this.g=a;
this.map=b;this.context=null},v5=function(a){g.$f.call(this,"statevent",a)},w5=function(a,b){g.$f.call(this,"timingevent",a);
this.size=b},x5=function(a){g.$f.call(this,"serverreachability",a)},B5=function(a){y5(a);
if(3==a.g){var b=a.Pj++,c=a.al.clone();g.Jn(c,"SID",a.l);g.Jn(c,"RID",b);g.Jn(c,"TYPE","terminate");z5(a,c);b=new V4(a,a.l,b,void 0);b.sh=2;b.Rf=b4(c.clone());(new Image).src=b.Rf;b.Vh=(0,g.C)();Z4(b)}A5(a)},D5=function(a){a.yB(1,0);
a.al=q5(a,null,a.Uo);C5(a)},y5=function(a){a.Hf&&(a.Hf.abort(),a.Hf=null);
a.Nb&&(a.Nb.cancel(),a.Nb=null);a.We&&(g.v.clearTimeout(a.We),a.We=null);E5(a);a.md&&(a.md.cancel(),a.md=null);a.Of&&(g.v.clearTimeout(a.Of),a.Of=null)},F5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Aoa(a.eG++,b));2!=a.g&&3!=a.g||C5(a)},C5=function(a){a.md||a.Of||(a.Of=k5((0,g.y)(a.Zx,a),0),a.nh=0)},I5=function(a,b){if(1==a.g){if(!b){a.Pj=Math.floor(1E5*Math.random());
var c=a.Pj++,d=new V4(a,"",c,void 0);d.yg=null;var e=G5(a),f=a.al.clone();g.Jn(f,"RID",c);g.Jn(f,"CVER","1");z5(a,f);X4(d,f,e);a.md=d;a.g=2}}else 3==a.g&&(b?H5(a,b):0==a.i.length||a.md||H5(a))},H5=function(a,b){if(b)if(6<a.rg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Pj-1;var d=G5(a)}else c=b.C,d=b.Qg;else c=a.Pj++,d=G5(a);var e=a.al.clone();g.Jn(e,"SID",a.l);g.Jn(e,"RID",c);g.Jn(e,"AID",a.Dh);z5(a,e);c=new V4(a,a.l,c,a.nh+1);c.yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.md=c;X4(c,e,d)},z5=function(a,b){if(a.Jc){var c=a.Jc.Fu();
c&&g.Xb(c,function(a,c){g.Jn(b,c,a)})}},G5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.rg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.rg?e:f-d;try{g.Xb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},J5=function(a){a.Nb||a.We||(a.C=1,a.We=k5((0,g.y)(a.Yx,a),0),a.kh=0)},L5=function(a){if(a.Nb||a.We||3<=a.kh)return!1;
a.C++;a.We=k5((0,g.y)(a.Yx,a),K5(a,a.kh));a.kh++;return!0},s5=function(a,b,c){a.pn=c;
a.te=b.jf;a.A||D5(a)},E5=function(a){null!=a.ug&&(g.v.clearTimeout(a.ug),a.ug=null)},K5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},N5=function(a,b){if(2==b||9==b){var c=null;
a.Jc&&(c=null);var d=(0,g.y)(a.gL,a);c||(c=new g.Bn("//www.google.com/images/cleardot.gif"),b4(c));m5(c.toString(),1E4,d)}else a5(2);M5(a,b)},M5=function(a,b){a.g=0;
a.Jc&&a.Jc.It(b);A5(a);y5(a)},A5=function(a){a.g=0;
a.te=-1;if(a.Jc)if(0==a.o.length&&0==a.i.length)a.Jc.lo();else{g.ob(a.o);var b=g.ob(a.i);a.o.length=0;a.i.length=0;a.Jc.lo(b)}},q5=function(a,b,c){var d=g.Kn(c);
if(""!=d.g)b&&g.Dn(d,b+"."+d.g),g.En(d,d.u);else{var e=window.location;d=moa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Oi&&g.Xb(a.Oi,function(a,b){g.Jn(d,b,a)});
g.Jn(d,"VER",a.rg);z5(a,d);return d},k5=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},a5=function(a){O5.dispatchEvent(new v5(O5,a))},P5=function(){},Boa=function(a,b){this.action=a;
this.params=b||{}},Q5=function(a,b){g.F.call(this);
this.g=new g.L(this.NJ,0,this);g.H(this,this.g);this.Lc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},R5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.mp;this.i=new Q5(this.BL,this);this.g=null;this.Ya=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.N=c||!1},Coa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.pn,sessionId:a.g.l,arrayId:a.g.Dh}},S5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&I5(a.g),B5(a.g));a.D=0},T5=function(a){return!!a.g&&3==a.g.g},Doa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},U5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Ih(a)||"";b&&(this.port=":"+b);this.domain=g.Hh(a)||"";a=g.Vb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ub(a,"10.0")&&(this.i=!1))},V5=function(a,b){var c=a.g;
if(g.Fa(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Rh(c+b,{})},W5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Va(a.o,d,!0),onError:g.Va(a.l,e),cd:g.Va(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.gr(b,a)},Eoa=function(){var a=X5;
Y5();Z5.push(a);$5(Z5)},a6=function(a,b){Y5();
var c=Z5,d=Foa(a,String(b));0==c.length?Goa(d):($5(c),(0,g.A)(c,function(a){a(d)}))},Y5=function(){Z5||(Z5=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",Z5,void 0))},Goa=function(a){var b=(b6+1)%50;
b6=b;c6[b]=a;d6||(d6=49==b)},$5=function(a){var b=c6;
if(b[0]){var c=b6,d=d6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(a){a(e)})}while(d!=c);
c6=Array(50);b6=-1;d6=!1}},Foa=function(a,b){var c=((0,g.C)()-Hoa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},e6=function(a){g.N.call(this);
this.C=a;this.g=[]},f6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Ioa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ce)(a.g,function(a){return!!z4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=f6(a,b[d])||c;return c},Joa=function(a,b){var c=a.g.length;
a.g=(0,g.Ce)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},g6=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ba=NaN},i6=function(a){e6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;h6(this);this.info("Initializing with "+x4(this.g))},j6=function(a){if(a.g.length){var b=(0,g.D)(a.g,function(a){return a.id}),c=V5(a.l,"/pairing/get_lounge_token_batch");
W5(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.aC,a),(0,g.y)(a.ZB,a))}},h6=function(a){var b=v4(H4());
b=(0,g.Ce)(b,function(a){return!a.uuid});
return Ioa(a,b)},k6=function(a,b){uoa((0,g.D)(a.g,u4));
b&&I4()},m6=function(a,b){g.N.call(this);
this.A=b;var c=g.Lt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;l6("Initialized with "+g.yh(this.g))},n6=function(a,b,c){var d=V5(a.u,"/pairing/get_screen_availability");
W5(a.u,d,{lounge_token:b.token},(0,g.y)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},o6=function(a,b){a:if(o4(b)!=o4(a.g))var c=!1;
else{c=g.dc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(l6("Updated online screens: "+g.yh(a.g)),a.g=b,a.M("screenChange"));Koa(a)},p6=function(a){isNaN(a.l)||g.uq(a.l);
a.l=g.sq((0,g.y)(a.kr,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},l6=function(a){a6("OnlineScreenService",a)},q6=function(a){var b={};
(0,g.A)(a.A(),function(a){a.token?b[a.token]=a.id:this.Fb("Requesting availability of screen w/o lounge token.")});
return b},Koa=function(a){a=g.dc(g.Yb(a.g,function(a){return a}));
g.yb(a);a.length?g.Kt("yt-remote-online-screen-ids",a.join(","),60):g.Mt("yt-remote-online-screen-ids")},r6=function(a){e6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Loa(this)},t6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.xd();if(k=(c?A4(k,c):null)||A4(k,b)){k.uuid=b;var l=s6(a,k);n6(a.i,l,function(a){e(a?l:null)})}else c?Moa(a,c,(0,g.y)(function(a){var f=s6(this,new s4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));n6(this.i,f,function(a){e(a?f:null)})},a),f):e(null)},u6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Moa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.gr(V5(a.A,"/pairing/get_lounge_token_batch"),e)},v6=function(a){a.g=a.l.xd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+x4(a.g))},Loa=function(a){w6(a);
a.l=new i6(a.A);a.l.subscribe("screenChange",(0,g.y)(a.jC,a));v6(a);a.o=v4(g.Lt("yt-remote-automatic-screen-cache")||[]);w6(a);a.info("Initializing automatic screens: "+x4(a.o));a.i=new m6(a.A,(0,g.y)(a.xd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.M("onlineScreenChange")},a))},s6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=A4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Kt("yt-remote-automatic-screen-cache",(0,g.D)(a.o,u4)));w6(a);a.u[b.uuid]=b.id;g.Kt("yt-remote-device-id-map",a.u,31536E3);return b},w6=function(a){a.u=g.Lt("yt-remote-device-id-map")||{}},x6=function(a,b,c){g.N.call(this);
this.K=c;this.F=a;this.i=b;this.l=null},y6=function(a,b){a6(a.K,b)},A6=function(a,b){x6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.HL,this);this.u=(0,g.y)(this.qK,this);this.o=g.sq((0,g.y)(function(){z6(this,null)},this),12E4)},Noa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yh(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.y)(function(){y6(this,"Failed to send message: getMdxSessionStatus.")},a)):y6(a,"Sending yt message without session: "+g.yh(b))},z6=function(a,b){g.uq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.rm,a),d=(0,g.y)(a.Ad,a);a.Ru(b,c,d,5)}}else a.Ad(Error("Waiting for session status timed out."))},B6=function(a,b,c){x6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.O=c;this.u=null;this.C=g.Ja;this.A=NaN;this.N=(0,g.y)(this.KL,this);this.g=g.Ja},C6=function(a){a.g=a.F.eA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(a){this.g=g.Ja;
this.rm(a)},a),(0,g.y)(function(a){this.g=g.Ja;
this.Ad(a)},a))},D6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.O;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}L4()&&(b.env_useStageMdx=1);return g.Ph(b)},E6=function(a,b){x6.call(this,a,b,"ManualSession");
this.g=g.sq((0,g.y)(this.Fh,this,null),150)},F6=function(a,b,c,d){g.N.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.ZI,this)},G6=function(a,b){return b?g.bb(a.l,function(a){return t4(b,a.label)},a):null},H6=function(a){a6("Controller",a)},X5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},I6=function(a){return a.u||!!a.l.length||!!a.g},J6=function(a,b,c){b!=a.g&&(g.Xf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Xx,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.Fh(null)):a.M("yt-remote-cast2-session-change",null))},K6=function(a){var b=a.i.dA(),c=a.g&&a.g.i;
a=(0,g.D)(b,function(a){c&&t4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=G6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Roa=function(a,b,c,d,e,f,k){Ooa()?Poa(b,e,f,k)&&(M6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?N6(a,c):(window.__onGCastApiAvailable=function(b,d){b?N6(a,c):(O6("Failed to load cast API: "+d),P6(!1),M6(!1),g.Mt("yt-remote-cast-available"),g.Mt("yt-remote-cast-receiver"),Q6(),c(!1))},d?g.Fq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?yoa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Q4():(S4(),P4(Qoa.map(woa))))):L6("Cannot initialize because not running Chrome")},Q6=function(){L6("dispose");
var a=R6();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);S6(!1);g.Aq(T6);T6.length=0},U6=function(){return!!g.Lt("yt-remote-cast-installed")},V6=function(){var a=g.Lt("yt-remote-cast-receiver");
return a?a.friendlyName:null},W6=function(){L6("clearCurrentReceiver");
g.Mt("yt-remote-cast-receiver")},X6=function(){return U6()?R6()?R6().getCastSession():(O6("getCastSelector: Cast is not initialized."),null):(O6("getCastSelector: Cast API is not installed!"),null)},Z6=function(){U6()?R6()?Y6()?(L6("Requesting cast selector."),R6().requestSession()):(L6("Wait for cast API to be ready to request the session."),T6.push(g.zq("yt-remote-cast2-api-ready",Z6))):O6("requestCastSelector: Cast is not initialized."):O6("requestCastSelector: Cast API is not installed!")},$6=
function(a,b){Y6()?R6().setConnectedScreenStatus(a,b):O6("setConnectedScreenStatus called before ready.")},Ooa=function(){var a=0<=g.Vb.search(/ (CrMo|Chrome|CriOS)\//);
return g.mx||a},Soa=function(a,b){R6().init(a,b)},Poa=function(a,b,c,d){var e=!1;
R6()||(a=new F6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Kt("yt-remote-cast-available",a);q4("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L6("onReceiverSelected: "+a.friendlyName);
g.Kt("yt-remote-cast-receiver",a);q4("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L6("onReceiverResumed: "+a.friendlyName);
g.Kt("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L6("onSessionChange: "+w4(a));
a||g.Mt("yt-remote-cast-receiver");q4("yt-remote-cast2-session-change",a)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L6("cloudview.createSingleton_: "+e);return e},R6=function(){return g.w("yt.mdx.remote.cloudview.instance_")},N6=function(a,b){P6(!0);
M6(!1);Soa(a,function(a){a?(S6(!0),g.Cq("yt-remote-cast2-api-ready")):(O6("Failed to initialize cast API."),P6(!1),g.Mt("yt-remote-cast-available"),g.Mt("yt-remote-cast-receiver"),Q6());b(a)})},L6=function(a){a6("cloudview",a)},O6=function(a){a6("cloudview",a)},P6=function(a){L6("setCastInstalled_ "+a);
g.Kt("yt-remote-cast-installed",a)},Y6=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},S6=function(a){L6("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M6=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},a7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.we=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},b7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.we=!1;a.hasNext=!1;a.C=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},c7=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},d7=function(a,b){a.C=b;
a.A=(0,g.C)()},e7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},f7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&b7(a)},g7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.pc(a.g);b.hasPrevious=a.we;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},j7=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new p4;this.l=this.i=null;this.F=(0,g.y)(this.NG,this);this.C=(0,g.y)(this.Qj,this);this.D=(0,g.y)(this.MG,this);this.H=(0,g.y)(this.aH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ls,this),h7(this))):c=3;0!=c&&(b?this.ls(c):g.sq((0,g.y)(function(){this.ls(c)},this),0));
var d=X6();d&&i7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},k7=function(a){return new a7(a.o.getPlayerContextData())},h7=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.A.push(this.o.subscribe(a,g.Va(this.VI,a),this))},a)},l7=function(a){(0,g.A)(a.A,function(a){this.o.unsubscribeByKey(a)},a);
a.A.length=0},m7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},o7=function(a,b,c){var d=k7(a);
d7(d,c);-1E3!=d.playerState&&(d.playerState=b);n7(a,d)},p7=function(a,b,c){a.o.sendMessage(b,c)},n7=function(a,b){l7(a);
a.o.setPlayerContextData(g7(b));h7(a)},i7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Qj(null));
a.l=b;a.l&&(a6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Qj(a.l.media[0]))},q7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=k7(a);b.contentId!=d.videoId&&a6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;d7(d,a.i.getEstimatedTime());n7(a,d)}else a6("CP","No cast media video. Ignoring state update.")},r7=function(a,b,c){return(0,g.y)(function(a){this.Fb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Fb("Retrying "+b+" using MDx browser channel."),p7(this,b,c))},a)},s7=function(a,b,c){g.N.call(this);
this.u=NaN;this.O=!1;this.H=this.F=this.N=this.K=NaN;this.R=[];this.o=this.C=this.l=this.Pa=this.g=null;this.na=a;this.R.push(g.fs(window,"beforeunload",(0,g.y)(this.TB,this)));this.i=[];this.Pa=new a7;this.Z=b.id;this.g=Toa(this,c);this.g.subscribe("handlerOpened",this.SG,this);this.g.subscribe("handlerClosed",this.OG,this);this.g.subscribe("handlerError",this.PG,this);this.g.subscribe("handlerMessage",this.QG,this);Doa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=this.Pa.videoId;
g.Nt()&&g.Kt("yt-remote-session-video-id",a)},this)},t7=function(a){a6("conn",a)},Toa=function(a,b){return new R5(V5(a.na,"/bc"),b)},u7=function(a,b){a.M("proxyStateChange",b)},Uoa=function(a){a.u=g.sq((0,g.y)(function(){t7("Connecting timeout");
this.A(1)},a),2E4)},v7=function(a){g.uq(a.u);
a.u=NaN},w7=function(a){g.uq(a.K);
a.K=NaN},Voa=function(a){x7(a);
a.N=g.sq((0,g.y)(function(){y7(this,"getNowPlaying")},a),2E4)},x7=function(a){g.uq(a.N);
a.N=NaN},A7=function(a,b){b&&(v7(a),w7(a));
b==(T5(a.g)&&isNaN(a.u))?b&&(u7(a,1),y7(a,"getSubtitlesTrack")):b?(a.P()&&a.Pa.reset(),u7(a,1),y7(a,"getNowPlaying"),z7(a)):a.A(1)},Woa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.jc(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.M("remotePlayerChange"))},B7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;f7(a.Pa,c,d);a.M("remoteQueueChange")},Xoa=function(a,b){b.params=b.params||{};
B7(a,b);C7(a,b);a.M("autoplayDismissed")},C7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
d7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Voa(a):x7(a);a.M("remotePlayerChange")},Yoa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);d7(a.Pa,isNaN(c)?0:c);a.M("remotePlayerChange")}},Zoa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.M("remotePlayerChange")},$oa=function(a,b){a.C=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},apa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.we="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.M("previousNextChange")},z7=function(a){g.uq(a.H);
a.H=g.sq((0,g.y)(a.A,a,1),864E5)},y7=function(a,b,c){c?t7("Sending: action="+b+", params="+g.yh(c)):t7("Sending: action="+b);
a.g.sendMessage(b,c)},D7=function(a){e6.call(this,"ScreenServiceProxy");
this.zc=a;this.i=[];this.i.push(this.zc.$_s("screenChange",(0,g.y)(this.FL,this)));this.i.push(this.zc.$_s("onlineScreenChange",(0,g.y)(this.xI,this)))},fpa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.lq("MDX_CONFIG")||b;soa();F4();E7||(E7=new U5(b?b.loungeApiHost:void 0),L4()&&(E7.g="/api/loungedev"));F7||(F7=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",F7,void 0));bpa();var c=G7();if(!c){var d=new r6(E7);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=G7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Roa(a,d,function(a){a?H7()&&$6(H7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){q4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),I7("Initializing: "+g.yh(b)),J7.push(g.zq("yt-remote-cast2-availability-change",function(){q4("yt-remote-receiver-availability-change")})),J7.push(g.zq("yt-remote-cast2-receiver-selected",function(){K7(null);
q4("yt-remote-auto-connect","cast-selector-receiver")})),J7.push(g.zq("yt-remote-cast2-receiver-resumed",function(){q4("yt-remote-receiver-resumed","cast-selector-receiver")})),J7.push(g.zq("yt-remote-cast2-session-change",cpa)),J7.push(g.zq("yt-remote-connection-change",function(a){a?$6(H7(),"YouTube TV"):L7()||($6(null,null),W6())})),a=M7(),b.isAuto&&(a.id+="#dial"),g.Nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),I7(" -- with channel params: "+
g.yh(a)),dpa(a),c.start(),H7()||epa())},gpa=function(){var a=N7();
U6()&&g.Lt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},N7=function(){var a=G7().zc.$_gos();
var b=O7();b&&P7()&&(z4(a,b)||a.push(b));return roa(a)},Q7=function(){var a=hpa();
!a&&U6()&&V6()&&(a={key:"cast-selector-receiver",name:V6()});return a},hpa=function(){var a=N7(),b=O7();
b||(b=L7());return g.bb(a,function(a){return b&&t4(b,a.key)?!0:!1})},O7=function(){var a=H7();
if(!a)return null;var b=G7().xd();return A4(b,a)},cpa=function(a){I7("remote.onCastSessionChange_: "+w4(a));
if(a){var b=O7();b&&b.id==a.id?$6(b.id,"YouTube TV"):(b&&R7(),S7(a,1))}else P7()&&R7()},R7=function(){Y6()?R6().stopSession():O6("stopSession called before API ready.");
var a=P7();a&&(a.disconnect(1),T7(null))},U7=function(){var a=P7();
return!!a&&3!=a.getProxyState()},I7=function(a){a6("remote",a)},G7=function(){if(!V7){var a=g.w("yt.mdx.remote.screenService_");
V7=a?new D7(a):null}return V7},H7=function(){return g.w("yt.mdx.remote.currentScreenId_")},W7=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},X7=function(){return g.w("yt.mdx.remote.connectData_")},K7=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},P7=function(){return g.w("yt.mdx.remote.connection_")},T7=function(a){var b=P7();
K7(null);a||W7("");g.Ia("yt.mdx.remote.connection_",a,void 0);F7&&((0,g.A)(F7,function(b){b(a)}),F7.length=0);
b&&!a?q4("yt-remote-connection-change",!1):!b&&a&&q4("yt-remote-connection-change",!0)},L7=function(){var a=g.Nt();
if(!a)return null;var b=G7().xd();return A4(b,a)},S7=function(a,b){O7()&&O7();
W7(a.id);var c=new s7(E7,a,M7());c.connect(b,X7());c.subscribe("beforeDisconnect",function(a){q4("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){P7()&&T7(null)});
T7(c)},epa=function(){var a=L7();
a?(I7("Resume connection to: "+w4(a)),S7(a,0)):(J4(),W6(),I7("Skipping connecting because no session screen found."))},bpa=function(){var a=M7();
if(g.jc(a)){a=E4();var b=g.Lt("yt-remote-session-name")||"",c=g.Lt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},M7=function(){return g.w("yt.mdx.remote.channelParams_")||{}},dpa=function(a){a?(g.Kt("yt-remote-session-app",a.app),g.Kt("yt-remote-session-name",a.name)):(g.Mt("yt-remote-session-app"),g.Mt("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},Y7=function(a,b,c){g.F.call(this);
this.u=a;this.i=b;this.l=new g.us(this);g.H(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.PH);this.l.J(b,"captionschanged",this.LG);this.l.J(b,"captionssettingschanged",this.sz);this.l.J(b,"videoplayerreset",this.sm);this.l.J(b,"mdxautoplaycancel",this.jB);this.R=this.l.J(b,"onVolumeChange",this.Ix);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Tx,this);c.subscribe("remotePlayerChange",this.Sj,this);c.subscribe("remoteQueueChange",this.sm,this);c.subscribe("autoplayUpNext",this.xx,
this);c.subscribe("previousNextChange",this.Qx,this);c.subscribe("nowAutoplaying",this.Mx,this);c.subscribe("autoplayDismissed",this.wx,this);this.suggestion=null;this.F=new g.eD(64);this.o=new g.L(this.qz,500,this);g.H(this,this.o);this.A=new g.L(this.rz,1E3,this);g.H(this,this.A);this.N=new T4(this.oL,0,this);g.H(this,this.N);this.C={};this.K=new g.L(this.Sz,1E3,this);g.H(this,this.K);this.H=new g.em(this.sE,1E3,this);g.H(this,this.H);this.O=g.Ja;this.sz();this.sm();this.Sj()},Z7=function(a,b){a.u.ed(b,
a.i.getVideoData().lengthSeconds)},a8=function(a){Z7(a,0);
a.o.stop();$7(a,new g.eD(64))},c8=function(a,b){if(b8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.rc(c,b));a.g.fz(a.i.getVideoData(1).videoId,c);a.C=k7(a.g).g}},d8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.xh,n4(c));$7(a,new g.eD(1))},e8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{YO:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},b8=function(a){return k7(a.g).videoId==a.i.getVideoData(1).videoId},$7=function(a,b){a.A.stop();
var c=a.F;if(!g.kD(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.TJ(a.i,d);a.F=b;f8(a.u,c,b)}},h8=function(a){g.T.call(this,{B:"div",
G:"ytp-remote",I:[{B:"div",G:"ytp-remote-display-status",I:[{B:"div",G:"ytp-remote-display-status-icon",I:[g.TO()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.i=new g.DP(this,250);g.H(this,this.i);this.l=a;this.J(a,"presentingplayerstatechange",this.o);g8(this,g.PJ(a))},g8=function(a,b){if(3==a.l.getPresentingPlayerType()){var c={RECEIVER_NAME:a.l.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.LN("Error on $RECEIVER_NAME",c):g.lD(b)||g.U(b,4)?g.LN("Playing on $RECEIVER_NAME",c):g.LN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.i.show()}else a.i.hide()},i8=function(a,b){g.jT.call(this,"Play on",0,a,b);
this.i=a;this.D={};this.J(a,"onMdxReceiversChange",this.H);this.J(a,"presentingplayerstatechange",this.H);this.H()},j8=function(a){g.rK.call(this,a);
this.i={key:y4(),name:"This computer"};this.o=null;this.u=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.Ej=new g.eD(64);this.D=0;this.Gl=-1;if(!g.kz(g.W(this.player))){a=this.player;var b=g.DC(a);b&&(b=b.Xl())&&(b=new i8(a,b),g.H(this,b));b=new h8(a);g.H(this,b);g.fK(a,b.element,4)}},f8=function(a,b,c){a.Ej=c;
a.player.M("presentingplayerstatechange",new g.qD(c,b))},k8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)R7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=n4(d))&&(c.locationInfo=d);d=c}else d=null;I7("Connecting to: "+g.yh(b));"cast-selector-receiver"==b.key?
(K7(d||null),Y6()?R6().setLaunchParams(d||null):O6("setLaunchParams called before ready.")):!d&&U7()&&H7()==b.key?q4("yt-remote-connection-change",!0):(R7(),K7(d||null),d=G7().xd(),(d=A4(d,b.key))&&S7(d,1))}},ioa=/^https?$/i,ipa=["POST",
"PUT"];g.z(l4,g.Cg);g.h=l4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.X=b;this.R=!1;this.i=!0;this.g=this.O?d4(this.O):d4(g.eY);this.K=this.O?this.O.getOptions():g.eY.getOptions();this.g.onreadystatechange=(0,g.y)(this.bv,this);try{a4(e4(this,"Opening Xhr")),this.Z=!0,this.g.open(b,String(a),!0),this.Z=!1}catch(f){a4(e4(this,"Error opening Xhr: "+f.message));i4(this,f);return}a=c||
"";var e=this.headers.clone();d&&foa(d,function(a,b){e.set(b,a)});
d=g.bb(e.wd(),goa);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(ipa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.W&&(this.g.responseType=this.W);"withCredentials"in this.g&&this.g.withCredentials!==this.P&&(this.g.withCredentials=this.P);try{f4(this),0<this.A&&(this.N=hoa(this.g),a4(e4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.N)),this.N?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.cv,this)):this.C=g.th(this.cv,this.A,this)),a4(e4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){a4(e4(this,"Send error: "+f.message)),i4(this,f)}};
g.h.cv=function(){"undefined"!=typeof g.KX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,e4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(e4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),h4(this,!0));l4.Ga.T.call(this)};
g.h.bv=function(){this.da()||(this.Z||this.D||this.o?k4(this):this.YI())};
g.h.YI=function(){k4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<j4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.t(this.l)?this.l:String(this.l)};
var h5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},g5={"'":"\\'"},jpa={};g.h=p4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.fb(this.g,a)||g.fb(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Nka)(b,a);0<=c?(g.ib(b,c),b=!0):b=!1;return b||g.jb(this.i,a)};
g.h.sc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var poa={dM:"atp",pO:"ska",fO:"que",GN:"mus",oO:"sus",XM:"dsp",lO:"seq"};r4.prototype.If=function(){var a=new r4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var K4,D4="",R4=M4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",xoa=M4("loadCastFramework")||M4("loadCastApplicationFramework"),Qoa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.z(T4,g.F);g.h=T4.prototype;g.h.QB=function(a){this.o=arguments;this.g=!1;this.Ba?this.l=(0,g.C)()+this.Lc:this.Ba=g.th(this.u,this.Lc)};
g.h.stop=function(){this.Ba&&(g.v.clearTimeout(this.Ba),this.Ba=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();T4.Ga.T.call(this)};
g.h.RB=function(){this.l?(this.Ba=g.th(this.u,this.l-(0,g.C)()),this.l=null):(this.Ba=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};U4.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
U4.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=V4.prototype;g.h.yg=null;g.h.ke=!1;g.h.ji=null;g.h.gs=null;g.h.Vh=null;g.h.sh=null;g.h.Rf=null;g.h.gg=null;g.h.Qg=null;g.h.hc=null;g.h.lk=0;g.h.me=null;g.h.un=null;g.h.Sf=null;g.h.ij=-1;g.h.Ty=!0;g.h.qg=!1;g.h.Xo=0;g.h.Gm=null;var b5={},$4={};g.h=V4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.EK=function(a){a=a.target;var b=this.Gm;b&&3==j4(a)?b.ej():this.Zz(a)};
g.h.Zz=function(a){try{if(a==this.hc)a:{var b=j4(this.hc),c=this.hc.u,d=this.hc.getStatus();if(g.ne&&!g.Vc(10)||g.pe&&!g.Tc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.qi&&!m4(this.hc))break a;this.qg||4!=b||7==c||(8==c||0>=d?this.g.fe(3):this.g.fe(2));l5(this);var e=this.hc.getStatus();this.ij=e;var f=m4(this.hc);(this.ke=200==e)?(4==b&&d5(this),this.u?(f5(this,b,f),g.qi&&this.ke&&3==b&&(this.aa.ca(this.i,"tick",this.AK),this.i.start())):c5(this,f),this.ke&&!this.qg&&(4==b?this.g.qm(this):(this.ke=
!1,Z4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Sf=3,a5(13)):(this.Sf=0,a5(14)),d5(this),e5(this))}}catch(k){this.hc&&m4(this.hc)}finally{}};
g.h.AK=function(){var a=j4(this.hc),b=m4(this.hc);this.lk<b.length&&(l5(this),f5(this,a,b),this.ke&&4!=a&&Z4(this))};
g.h.VJ=function(a){k5((0,g.y)(this.UJ,this,a),0)};
g.h.UJ=function(a){this.qg||(l5(this),c5(this,a),Z4(this))};
g.h.ay=function(a){k5((0,g.y)(this.TJ,this,a),0)};
g.h.TJ=function(a){this.qg||(d5(this),this.ke=a,this.g.qm(this),this.g.fe(4))};
g.h.cancel=function(){this.qg=!0;d5(this)};
g.h.fK=function(){this.ji=null;var a=(0,g.C)();0<=a-this.gs?(2!=this.sh&&this.g.fe(3),d5(this),this.Sf=2,a5(18),e5(this)):j5(this,this.gs-a)};
g.h.getLastError=function(){return this.Sf};g.h=p5.prototype;g.h.Vo=null;g.h.Cd=null;g.h.Hm=!1;g.h.av=null;g.h.Yk=null;g.h.Np=null;g.h.Wo=null;g.h.Pd=null;g.h.jf=-1;g.h.hj=null;g.h.Bi=null;g.h.connect=function(a){this.Wo=a;a=q5(this.g,null,this.Wo);a5(3);this.av=(0,g.C)();var b=this.g.D;null!=b?(this.hj=b[0],(this.Bi=b[1])?(this.Pd=1,r5(this)):(this.Pd=2,t5(this))):(c4(a,"MODE","init"),this.Cd=new V4(this,void 0,void 0,void 0),this.Cd.yg=this.Vo,Y4(this.Cd,a,!1,null,!0),this.Pd=0)};
g.h.kB=function(a){if(a)this.Pd=2,t5(this);else{a5(4);var b=this.g;b.te=b.Hf.jf;N5(b,9)}a&&this.fe(2)};
g.h.wo=function(a){return this.g.wo(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.jf=-1};
g.h.Zu=function(){return!1};
g.h.Ux=function(a,b){this.jf=a.ij;if(0==this.Pd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.te=this.jf;N5(c,2);return}this.hj=c[0];this.Bi=c[1]}else c=this.g,c.te=this.jf,N5(c,2);else if(2==this.Pd)if(this.Hm)a5(7),this.Np=(0,g.C)();else if("11111"==b){if(a5(6),this.Hm=!0,this.Yk=(0,g.C)(),c=this.Yk-this.av,!g.ne||g.Vc(10)||500>c)this.jf=200,this.Cd.cancel(),a5(12),s5(this.g,this,!0)}else a5(8),this.Yk=this.Np=(0,g.C)(),this.Hm=!1};
g.h.qm=function(){this.jf=this.Cd.ij;if(this.Cd.ke)0==this.Pd?this.Bi?(this.Pd=1,r5(this)):(this.Pd=2,t5(this)):2==this.Pd&&((!g.ne||g.Vc(10)?!this.Hm:200>this.Np-this.Yk)?(a5(11),s5(this.g,this,!1)):(a5(12),s5(this.g,this,!0)));else{0==this.Pd?a5(9):2==this.Pd&&a5(10);var a=this.g;a.te=this.jf;N5(a,2)}};
g.h.ck=function(){return this.g.ck()};
g.h.isActive=function(){return this.g.isActive()};
g.h.fe=function(a){this.g.fe(a)};g.h=u5.prototype;g.h.Oi=null;g.h.md=null;g.h.Nb=null;g.h.Uo=null;g.h.al=null;g.h.At=null;g.h.ol=null;g.h.Pj=0;g.h.eG=0;g.h.Jc=null;g.h.Of=null;g.h.We=null;g.h.ug=null;g.h.Hf=null;g.h.pn=null;g.h.Dh=-1;g.h.Gv=-1;g.h.te=-1;g.h.nh=0;g.h.kh=0;g.h.rg=8;var O5=new g.Cg;g.z(v5,g.$f);g.z(w5,g.$f);g.z(x5,g.$f);g.h=u5.prototype;g.h.connect=function(a,b,c,d,e){a5(0);this.Uo=b;this.Oi=c||{};d&&g.Fa(e)&&(this.Oi.OSID=d,this.Oi.OAID=e);this.A?(k5((0,g.y)(this.Rt,this,a),100),D5(this)):this.Rt(a)};
g.h.Rt=function(a){this.Hf=new p5(this);this.Hf.Vo=null;this.Hf.i=this.u;this.Hf.connect(a)};
g.h.Zu=function(){return 0==this.g};
g.h.Zx=function(a){this.Of=null;I5(this,a)};
g.h.Yx=function(){this.We=null;this.Nb=new V4(this,this.l,"rpc",this.C);this.Nb.yg=null;this.Nb.Xo=0;var a=this.At.clone();g.Jn(a,"RID","rpc");g.Jn(a,"SID",this.l);g.Jn(a,"CI",this.pn?"0":"1");g.Jn(a,"AID",this.Dh);z5(this,a);if(!g.ne||g.Vc(10))g.Jn(a,"TYPE","xmlhttp"),Y4(this.Nb,a,!0,this.ol,!1);else{g.Jn(a,"TYPE","html");var b=this.Nb,c=!!this.ol;b.sh=3;b.Rf=b4(a.clone());i5(b,c)}};
g.h.Ux=function(a,b){if(0!=this.g&&(this.Nb==a||this.md==a))if(this.te=a.ij,this.md==a&&3==this.g)if(7<this.rg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.We){if(this.Nb)if(this.Nb.Vh+3E3<this.md.Vh)E5(this),this.Nb.cancel(),this.Nb=null;else break a;L5(this);a5(19)}}else this.Gv=c[1],0<this.Gv-this.Dh&&37500>c[2]&&this.pn&&0==this.kh&&!this.ug&&(this.ug=k5((0,g.y)(this.HG,this),6E3));else N5(this,11)}else b!=jpa.CM.g&&N5(this,11);else if(this.Nb==a&&
E5(this),!g.Ib(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.Dh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.ol=e[2],e=e[3],null!=e?this.rg=e:this.rg=6,this.g=3,this.Jc&&this.Jc.Kt(),this.At=q5(this,this.ck()?this.ol:null,this.Uo),J5(this)):"stop"==e[0]&&N5(this,7):3==this.g&&("stop"==e[0]?N5(this,7):"noop"!=e[0]&&this.Jc&&this.Jc.Jt(e),this.kh=0)}}};
g.h.HG=function(){null!=this.ug&&(this.ug=null,this.Nb.cancel(),this.Nb=null,L5(this),a5(20))};
g.h.qm=function(a){if(this.Nb==a){E5(this);this.Nb=null;var b=2}else if(this.md==a)this.md=null,b=1;else return;this.te=a.ij;if(0!=this.g)if(a.ke)1==b?(b=(0,g.C)()-a.Vh,O5.dispatchEvent(new w5(O5,a.Qg?a.Qg.length:0,b,this.nh)),C5(this),this.o.length=0):J5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.te)){if(d=1==b)this.md||this.Of||1==this.g||2<=this.nh?d=!1:(this.Of=k5((0,g.y)(this.Zx,this,a),K5(this,this.nh)),this.nh++,d=!0);d=!(d||2==b&&L5(this))}if(d)switch(c){case 1:N5(this,
5);break;case 4:N5(this,10);break;case 3:N5(this,6);break;case 7:N5(this,12);break;default:N5(this,2)}}};
g.h.yB=function(a){if(!g.fb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.gL=function(a){a?a5(2):(a5(1),M5(this,8))};
g.h.wo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new l4;a.P=!1;return a};
g.h.isActive=function(){return!!this.Jc&&this.Jc.isActive(this)};
g.h.fe=function(a){O5.dispatchEvent(new x5(O5,a))};
g.h.ck=function(){return!(!g.ne||g.Vc(10))};
g.h=P5.prototype;g.h.Kt=function(){};
g.h.Jt=function(){};
g.h.It=function(){};
g.h.lo=function(){};
g.h.Fu=function(){return{}};
g.h.isActive=function(){return!0};g.z(Q5,g.F);g.h=Q5.prototype;g.h.NJ=function(){this.Lc=Math.min(3E5,2*this.Lc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Lc+15E3*Math.random();g.Ro(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Lc=5E3};g.z(R5,P5);g.h=R5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.rf=function(a){return this.l.zg(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Ya||(this.Ya=!0,g.Xf(this.l),S5(this),g.Xf(this.i),this.i=null)};
g.h.da=function(){return this.Ya};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new u5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.Jc=null);d.Jc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Dh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.rc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):T5(this)&&F5(this.g,c)};
g.h.Kt=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)F5(this.g,a[b])}this.M("handlerOpened")};
g.h.It=function(a){var b=2==a&&401==this.g.te;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.lo=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Fu=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.rc(a,this.u);return a};
g.h.Jt=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),B5(this.g)):this.M("handlerMessage",new Boa(a[0],a[1]))};
g.h.BL=function(){this.i.isActive();var a=this.g,b=0;a.Nb&&b++;a.md&&b++;0!=b||this.connect(this.u,this.o)};U5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
U5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
U5.prototype.u=function(a){a(Error("request timed out"))};var Hoa=(0,g.C)(),Z5=null,c6=Array(50),b6=-1,d6=!1;g.z(e6,g.N);e6.prototype.xd=function(){return this.g};
e6.prototype.contains=function(a){return!!z4(this.g,a)};
e6.prototype.get=function(a){return a?A4(this.g,a):null};
e6.prototype.info=function(a){a6(this.C,a)};g.z(g6,g.N);var l8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=g6.prototype;g.h.start=function(){!this.g&&isNaN(this.Ba)&&this.cA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ba)||(g.uq(this.Ba),this.Ba=NaN)};
g.h.T=function(){this.stop();g6.Ga.T.call(this)};
g.h.cA=function(){this.Ba=NaN;this.g=g.gr(V5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.DL,this),onError:(0,g.y)(this.CL,this),cd:(0,g.y)(this.EL,this)})};
g.h.DL=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new s4(c))};
g.h.CL=function(a){this.g=null;a.status&&404==a.status?this.i>=l8.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=l8[this.i],this.Ba=g.sq((0,g.y)(this.cA,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.EL=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};g.z(i6,e6);g.h=i6.prototype;g.h.start=function(){h6(this)&&this.M("screenChange");!g.Lt("yt-remote-lounge-token-expiration")&&j6(this);g.uq(this.i);this.i=g.sq((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){h6(this);f6(this,a);k6(this,!1);this.M("screenChange");b(a);a.token||j6(this)};
g.h.remove=function(a,b){var c=h6(this);Joa(this,a)&&(k6(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.kn=function(a,b,c,d){var e=h6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.uq(this.i);i6.Ga.T.call(this)};
g.h.aC=function(a){h6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k6(this,!b);b&&a6(this.C,"Missed "+b+" lounge tokens.")};
g.h.ZB=function(a){a6(this.C,"Requesting lounge tokens failed: "+a)};g.z(m6,g.N);g.h=m6.prototype;g.h.start=function(){var a=parseInt(g.Lt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?p6(this):(this.o=(0,g.C)()+3E5,g.Kt("yt-remote-fast-check-period",this.o),this.kr())};
g.h.isEmpty=function(){return g.jc(this.g)};
g.h.update=function(){l6("Updating availability on schedule.");var a=this.A(),b=g.Yb(this.g,function(b,d){return b&&!!A4(a,d)},this);
o6(this,b)};
g.h.T=function(){g.uq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);m6.Ga.T.call(this)};
g.h.kr=function(){g.uq(this.l);this.l=NaN;this.i&&this.i.abort();var a=q6(this);if(o4(a)){var b=V5(this.u,"/pairing/get_screen_availability");this.i=W5(this.u,b,{lounge_token:g.dc(a).join(",")},(0,g.y)(this.uJ,this,a),(0,g.y)(this.tJ,this))}else o6(this,{}),p6(this)};
g.h.uJ=function(a,b){this.i=null;var c=g.dc(q6(this));if(g.Bb(c,g.dc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;o6(this,d);p6(this)}else this.Fb("Changing Screen set during request."),this.kr()};
g.h.tJ=function(a){this.Fb("Screen availability failed: "+a);this.i=null;p6(this)};
g.h.Fb=function(a){a6("OnlineScreenService",a)};g.z(r6,e6);g.h=r6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.kn=function(a,b,c,d){this.l.contains(a)?this.l.kn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,a6(this.C,a),d(Error(a)))};
g.h.xd=function(a){return a?this.g:g.nb(this.g,(0,g.Ce)(this.o,function(a){return!this.contains(a)},this))};
g.h.dA=function(){return(0,g.Ce)(this.xd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.eA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new g6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(a){g.Xf(f);d(s6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Xf(f);e(a)});
f.start();return(0,g.y)(f.stop,f)};
g.h.GL=function(a,b,c,d){g.gr(V5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(a,d){var e=new s4(d.screen||{});if(!e.name||u6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);u6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(s6(this,e))},this),
onError:(0,g.y)(function(a){d(Error("pairing request failed: "+a.status))},this),
cd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.Xf(this.l);g.Xf(this.i);r6.Ga.T.call(this)};
g.h.jC=function(){v6(this);this.M("screenChange");this.i.update()};
r6.prototype.dispose=r6.prototype.dispose;g.z(x6,g.N);g.h=x6.prototype;g.h.rm=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Ad=function(a){this.da()||(a&&y6(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){a6(this.K,a)};
g.h.gA=function(){return null};
g.h.zr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){y6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.zr("");x6.Ga.T.call(this)};g.z(A6,x6);g.h=A6.prototype;g.h.yr=function(a){if(this.g){if(this.g==a)return;y6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Noa(this)};
g.h.Fh=function(a){this.info("launchWithParams no-op for Cast: "+g.yh(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Ad()},this),(0,g.y)(function(){this.Ad(Error("Failed to stop receiver app."))},this)):this.Ad(Error("Stopping cast device witout session."))};
g.h.zr=g.Ja;g.h.T=function(){this.info("disposeInternal");g.uq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;A6.Ga.T.call(this)};
g.h.qK=function(a,b){if(!this.da())if(b){var c=g.bp(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yh(c));switch(d){case "mdxSessionStatus":z6(this,c.screenId);break;default:y6(this,"Unknown youtube message: "+d)}}else y6(this,"Unable to parse message.")}else y6(this,"No data in message.")};
g.h.Ru=function(a,b,c,d){t6(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(y6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.sq((0,g.y)(this.Ru,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.gA=function(){return this.g};
g.h.HL=function(a){this.da()||a||(y6(this,"Cast session died."),this.Ad())};g.z(B6,x6);g.h=B6.prototype;g.h.yr=function(a){this.o=a;this.o.addUpdateListener(this.N)};
g.h.Fh=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.uq(this.A);this.o?this.o.stop((0,g.y)(this.Ad,this,null),(0,g.y)(this.Ad,this,"Failed to stop DIAL device.")):this.Ad()};
g.h.T=function(){this.g();this.g=g.Ja;g.uq(this.A);this.o&&this.o.removeUpdateListener(this.N);this.o=null;B6.Ga.T.call(this)};
g.h.KL=function(a){this.da()||a||(y6(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Ad())};
g.h.pp=function(a){this.H=y4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)}else this.C=(0,g.y)(function(){g.uq(this.A);this.C=g.Ja;this.A=NaN;var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)},this),this.A=g.sq((0,g.y)(function(){this.C()},this),100)};
g.h.GC=function(a,b,c){t6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(a){a&&a.token?(this.rm(a),b(new chrome.cast.DialLaunchResponse(!1))):this.pp(b,c)},this),(0,g.y)(function(a){y6(this,"Failed to get DIAL screen: "+a);
this.pp(b,c)},this))};g.z(E6,x6);E6.prototype.stop=function(){this.Ad()};
E6.prototype.yr=g.Ja;E6.prototype.Fh=function(){g.uq(this.g);this.g=NaN;var a=A4(this.F.xd(),this.i.label);a?this.rm(a):this.Ad(Error("No such screen"))};
E6.prototype.T=function(){g.uq(this.g);this.g=NaN;E6.Ga.T.call(this)};g.z(F6,g.N);g.h=F6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Wx,this),(0,g.y)(this.dJ,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.jH,this);chrome.cast.initialize(c,(0,g.y)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),Eoa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.fA,this)),this.l=K6(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.y)(function(a){this.Fb("Failed to set initial custom receivers: "+g.yh(a))},this)),this.M("yt-remote-cast2-availability-change",I6(this)),b(!0))},this),(0,g.y)(function(a){this.Fb("Failed to initialize API: "+g.yh(a));
b(!1)},this))};
g.h.WK=function(a,b){H6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)H6("Unsetting old screen status: "+this.g.i.friendlyName),J6(this,null)}if(a&&b){if(!this.g){c=A4(this.i.xd(),a);if(!c){H6("setConnectedScreenStatus: Unknown screen.");return}var d=G6(this,c);d||(H6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.y)(function(a){this.Fb("Failed to set initial custom receivers: "+g.yh(a))},this)));
H6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);J6(this,new E6(this.i,d),!0)}this.g.zr(b)}else H6("setConnectedScreenStatus: no screen.")};
g.h.XK=function(a){this.da()?this.Fb("Setting connection data on disposed cast v2"):this.g?this.g.Fh(a):this.Fb("Setting connection data without a session")};
g.h.JL=function(){this.da()?this.Fb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),J6(this,null)):H6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Wx,this),(0,g.y)(this.zJ,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.fA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.jb(g.w("yt.mdx.remote.debug.handlers_")||[],X5);g.Xf(this.g);F6.Ga.T.call(this)};
g.h.Fb=function(a){a6("Controller",a)};
g.h.Xx=function(a,b){this.g==a&&(b||J6(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.ZI=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),H6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)H6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{H6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:J6(this,
new E6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:J6(this,new B6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:J6(this,new A6(this.i,a));break;default:this.Fb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Fb("Stopping receiver w/o session: "+a.friendlyName)}else this.Fb("onReceiverAction_ called without receiver.")};
g.h.jH=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Fb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Fb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return H6("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Fb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);J6(this,new B6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.GC,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.pp,b))};
g.h.Wx=function(a){if(!this.da()){H6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)H6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),J6(this,new A6(this.i,b),!0);else{this.Fb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=A4(this.i.xd(),c.label);d&&t4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(H6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Xf(this.g),this.g=new A6(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Xx,this,this.g)),this.g.Fh(null));this.g.yr(a)}}};
g.h.IL=function(){return this.g?this.g.gA():null};
g.h.zJ=function(a){this.da()||(this.Fb("Failed to estabilish a session: "+g.yh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&J6(this,null))};
g.h.dJ=function(a){H6("Receiver availability updated: "+a);if(!this.da()){var b=I6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;I6(this)!=b&&this.M("yt-remote-cast2-availability-change",I6(this))}};
g.h.fA=function(){this.da()||(this.l=K6(this),H6("Updating custom receivers: "+g.yh(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.y)(function(){this.Fb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",I6(this)))};
F6.prototype.setLaunchParams=F6.prototype.XK;F6.prototype.setConnectedScreenStatus=F6.prototype.WK;F6.prototype.stopSession=F6.prototype.JL;F6.prototype.getCastSession=F6.prototype.IL;F6.prototype.requestSession=F6.prototype.requestSession;F6.prototype.init=F6.prototype.init;F6.prototype.dispose=F6.prototype.dispose;var T6=[];a7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";b7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.we=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
a7.prototype.isAdPlaying=function(){return 1081==this.playerState};
a7.prototype.getDuration=function(){return this.u?this.D+c7(this):this.D};
a7.prototype.clone=function(){return new a7(g7(this))};g.z(j7,g.N);g.h=j7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,r7(this,"play")):p7(this,"play"),o7(this,1,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,r7(this,"pause")):p7(this,"pause"),o7(this,2,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=k7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,r7(this,"seekTo",{newTime:a}))}else p7(this,"seekTo",{newTime:a});o7(this,3,a);this.M("remotePlayerChange")}else m7(this,g.Va(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,r7(this,"stopVideo")):p7(this,"stopVideo");var a=k7(this);a.index=-1;a.videoId="";b7(a);n7(this,a);this.M("remotePlayerChange")}else m7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=k7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){a6("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Fb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){a6("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Fb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);p7(this,"setVolume",e)}c.muted=b;c.volume=a;n7(this,c)}else m7(this,g.Va(this.setVolume,a,b))};
g.h.fz=function(a,b){if(1==this.g){var c=k7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yh(b.style),g.rc(d,c.g));p7(this,"setSubtitlesTrack",d);n7(this,c)}else m7(this,g.Va(this.fz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){p7(this,"setAudioTrack",{videoId:a,audioTrackId:b.kb.id});var c=k7(this);c.audioTrackId=b.kb.id;n7(this,c)}else m7(this,g.Va(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=k7(this);c=c||0;var m={videoId:a,currentIndex:c};f7(l,a,c);g.Fa(b)&&(d7(l,b),m.currentTime=b);g.Fa(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.yh(k));p7(this,"setPlaylist",m);d||n7(this,l)};
g.h.Am=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"previous")}else m7(this,g.Va(this.Am,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"next")}else m7(this,g.Va(this.nextVideo,a,b))};
g.h.ju=function(){1==this.g?p7(this,"dismissAutoplay"):m7(this,this.ju)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}j7.Ga.dispose.call(this)};
g.h.T=function(){l7(this);this.o=null;this.u.clear();i7(this,null);j7.Ga.T.call(this)};
g.h.ls=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.VI=function(a,b){this.M(a,b)};
g.h.NG=function(a){if(!a)this.Qj(null),i7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=k7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)a6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,n7(this,b)}};
g.h.Qj=function(a){a6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),q7(this),this.M("remotePlayerChange")};
g.h.MG=function(a){a?(q7(this),this.M("remotePlayerChange")):this.Qj(null)};
g.h.Or=function(){p7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.aH=function(){var a=X6();a&&i7(this,a)};
g.h.Fb=function(a){a6("CP",a)};g.z(s7,g.N);g.h=s7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Fa(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Fa(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;d7(this.Pa,m);this.o="UNSUPPORTED";t7("Connecting with setPlaylist and params: "+g.yh(l));this.g.connect({method:"setPlaylist",
params:g.yh(l)},a,G4())}else t7("Connecting without params"),this.g.connect({},a,G4());Uoa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),u7(this,3));s7.Ga.dispose.call(this)};
g.h.T=function(){v7(this);x7(this);w7(this);g.uq(this.F);this.F=NaN;g.uq(this.H);this.H=NaN;this.l=null;g.gs(this.R);this.R.length=0;this.g.dispose();s7.Ga.T.call(this);this.o=this.C=this.i=this.Pa=this.g=null};
g.h.TB=function(){this.A(2)};
g.h.SG=function(){t7("Channel opened");this.O&&(this.O=!1,w7(this),this.K=g.sq((0,g.y)(function(){t7("Timing out waiting for a screen.");this.A(1)},this),15E3));
voa(Coa(this.g),this.Z)};
g.h.OG=function(){t7("Channel closed");isNaN(this.u)?J4(!0):J4();this.dispose()};
g.h.PG=function(a){J4();isNaN(this.D())?(t7("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,t7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),u7(this,2))};
g.h.QG=function(a){a.params?t7("Received: action="+a.action+", params="+g.yh(a.params)):t7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.bp(a.params.devices);this.i=(0,g.D)(a,function(a){return new r4(a)});
a=!!g.bb(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,a);break;case "loungeScreenDisconnected":g.kb(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,!1);break;case "remoteConnected":var b=new r4(g.bp(a.params.device));g.bb(this.i,function(a){return b?a.id==b.id:!1})||loa(this.i,b);
break;case "remoteDisconnected":b=new r4(g.bp(a.params.device));g.kb(this.i,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":B7(this,a);break;case "nowPlaying":Xoa(this,a);break;case "onStateChange":C7(this,a);break;case "onAdStateChange":Yoa(this,a);break;case "onVolumeChanged":Zoa(this,a);break;case "onSubtitlesTrackChanged":Woa(this,a);break;case "nowAutoplaying":$oa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.M("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":apa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:t7("Unrecognized action: "+a.action)}};
g.h.KK=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&y7(this,"getNowPlaying")}};
s7.prototype.subscribe=s7.prototype.subscribe;s7.prototype.unsubscribeByKey=s7.prototype.rf;s7.prototype.ba=function(){var a=3;this.da()||(a=0,isNaN(this.D())?T5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
s7.prototype.getProxyState=s7.prototype.ba;s7.prototype.A=function(a){t7("Disconnecting with "+a);v7(this);this.M("beforeDisconnect",a);1==a&&J4();S5(this.g,a);this.dispose()};
s7.prototype.disconnect=s7.prototype.A;s7.prototype.ga=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),f7(a,this.l,a.index));return g7(a)};
s7.prototype.getPlayerContextData=s7.prototype.ga;
s7.prototype.la=function(a){var b=new a7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.uq(this.F),this.F=g.sq((0,g.y)(this.KK,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&e7(this.Pa)==e7(b)&&g.yh(this.Pa.g)==g.yh(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.A)(c,function(a){this.M(a)},this)};
s7.prototype.setPlayerContextData=s7.prototype.la;s7.prototype.P=function(){var a=this.g.A.id,b=g.bb(this.i,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
s7.prototype.getOtherConnectedRemoteId=s7.prototype.P;s7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
s7.prototype.getReconnectTimeout=s7.prototype.D;s7.prototype.X=function(){return this.o||"UNSUPPORTED"};
s7.prototype.getAutoplayMode=s7.prototype.X;s7.prototype.W=function(){return this.C||""};
s7.prototype.getAutoplayVideoId=s7.prototype.W;s7.prototype.sa=function(){if(!isNaN(this.D())){var a=this.g.i;g.So(a.g);a.start()}};
s7.prototype.reconnect=s7.prototype.sa;s7.prototype.ia=function(a,b){y7(this,a,b);z7(this)};
s7.prototype.sendMessage=s7.prototype.ia;g.z(D7,e6);g.h=D7.prototype;g.h.xd=function(a){return this.zc.$_gs(a)};
g.h.contains=function(a){return!!this.zc.$_c(a)};
g.h.get=function(a){return this.zc.$_g(a)};
g.h.start=function(){this.zc.$_st()};
g.h.add=function(a,b,c){this.zc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.zc.$_r(a,b,c)};
g.h.kn=function(a,b,c,d){this.zc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.zc.$_ubk(this.i[a]);this.i.length=0;this.zc=null;D7.Ga.T.call(this)};
g.h.FL=function(){this.M("screenChange")};
g.h.xI=function(){this.M("onlineScreenChange")};
r6.prototype.$_st=r6.prototype.start;r6.prototype.$_gspc=r6.prototype.GL;r6.prototype.$_gsppc=r6.prototype.eA;r6.prototype.$_c=r6.prototype.contains;r6.prototype.$_g=r6.prototype.get;r6.prototype.$_a=r6.prototype.add;r6.prototype.$_un=r6.prototype.kn;r6.prototype.$_r=r6.prototype.remove;r6.prototype.$_gs=r6.prototype.xd;r6.prototype.$_gos=r6.prototype.dA;r6.prototype.$_s=r6.prototype.subscribe;r6.prototype.$_ubk=r6.prototype.rf;var E7=null,F7=null,V7=null,J7=[];g.r(Y7,g.F);g.h=Y7.prototype;
g.h.T=function(){g.F.prototype.T.call(this);this.o.stop();this.A.stop();this.N.stop();this.O();this.g.unsubscribe("proxyStateChange",this.Tx,this);this.g.unsubscribe("remotePlayerChange",this.Sj,this);this.g.unsubscribe("remoteQueueChange",this.sm,this);this.g.unsubscribe("autoplayUpNext",this.xx,this);this.g.unsubscribe("previousNextChange",this.Qx,this);this.g.unsubscribe("nowAutoplaying",this.Mx,this);this.g.unsubscribe("autoplayDismissed",this.wx,this);this.g=this.u=null};
g.h.tw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(b8(this)){if(!k7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==k7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.ej(c[0],c[1]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();d8(this,0==c?void 0:c);break;case "control_seek":d8(this,c[0]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.LG=function(a){this.N.QB(a)};
g.h.oL=function(a){this.tw("control_subtitles_set_track",g.jc(a)?null:a)};
g.h.sz=function(){var a=this.i.getOption("captions","track");g.jc(a)||c8(this,a)};
g.h.Ix=function(a){if(b8(this)){this.g.unsubscribe("remotePlayerChange",this.Sj,this);var b=Math.round(a.volume);a=!!a.muted;var c=k7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.Sj,this)}};
g.h.PH=function(){g.jc(this.C)||e8(this,this.C);this.D=!1};
g.h.Tx=function(a,b){this.A.stop();2==b&&this.rz()};
g.h.Sj=function(){if(b8(this)){this.o.stop();var a=k7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Gl=1;break;case 1082:case 1083:this.u.Gl=0;break;default:this.u.Gl=-1}switch(a.playerState){case 1081:case 1:$7(this,new g.eD(8));this.qz();break;case 1085:case 3:$7(this,new g.eD(9));break;case 1083:case 0:$7(this,new g.eD(2));this.H.stop();Z7(this,this.i.getVideoData().lengthSeconds);break;case 1084:$7(this,new g.eD(4));break;case 2:$7(this,new g.eD(4));Z7(this,e7(a));
break;case -1:$7(this,new g.eD(64));break;case -1E3:$7(this,new g.eD(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=k7(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,e8(this,a));a=k7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.K.isActive()||this.Sz()}else a8(this)};
g.h.Qx=function(){this.i.M("mdxpreviousnextchange")};
g.h.sm=function(){b8(this)||a8(this)};
g.h.jB=function(){this.g.ju()};
g.h.xx=function(a){a&&(a=g.gr("/watch_queue_ajax",{method:"GET",wc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.YJ,this)}))&&(this.O=(0,g.y)(a.abort,a))};
g.h.YJ=function(a,b){var c=new g.lB(g.W(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.Mx=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.wx=function(){this.i.M("mdxautoplaycanceled")};
g.h.sE=function(a,b){-1==k7(this.g).playerState?d8(this,a):b&&this.g.seekTo(a)};
g.h.Sz=function(){if(b8(this)){var a=k7(this.g);this.l.La(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.J(this.i,"onVolumeChange",this.Ix)}};
g.h.qz=function(){this.o.stop();if(!this.g.da()){var a=k7(this.g);1==a.playerState&&$7(this,new g.eD(8));Z7(this,e7(a));this.o.start()}};
g.h.rz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.r(h8,g.T);h8.prototype.o=function(a){g8(this,a.state)};g.r(i8,g.jT);i8.prototype.H=function(){var a=this.i.getOption("remote","receivers");a&&1<a.length&&!this.i.getOption("remote","quickCast")?(this.D=g.Db(a,this.u,this),g.lT(this,(0,g.D)(a,this.u)),a=this.i.getOption("remote","currentReceiver"),this.He(this.u(a)),this.enable(!0)):this.enable(!1)};
i8.prototype.u=function(a){return a.key};
i8.prototype.Ud=function(a){return"cast-selector-receiver"==a?"Cast...":this.D[a].name};
i8.prototype.Oc=function(a){g.jT.prototype.Oc.call(this,a);this.i.setOption("remote","currentReceiver",this.D[a]);this.l.fb()};g.r(j8,g.rK);g.h=j8.prototype;g.h.create=function(){fpa(g.cz(g.W(this.player)));this.u.push(g.zq("yt-remote-before-disconnect",this.IG,this));this.u.push(g.zq("yt-remote-connection-change",this.eJ,this));this.u.push(g.zq("yt-remote-receiver-availability-change",this.Rx,this));this.u.push(g.zq("yt-remote-auto-connect",this.cJ,this));this.u.push(g.zq("yt-remote-receiver-resumed",this.bJ,this));this.Rx()};
g.h.load=function(){this.player.cancelPlayback();g.rK.prototype.load.call(this);this.o=new Y7(this,this.player,this.g);var a=(a=X7())?a.currentTime:0;var b=U7()?new j7(P7(),void 0):null;0==a&&b&&(a=e7(k7(b)));0!=a&&this.ed(a);f8(this,this.Ej,this.Ej);g.fX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.Yf(this.o,this.g);this.g=this.o=null;g.rK.prototype.unload.call(this);g.fX(this.player.app,5)};
g.h.T=function(){g.Aq(this.u);g.rK.prototype.T.call(this)};
g.h.Je=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.tw.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Gl};
g.h.NB=function(){return this.loaded?this.o.suggestion:null};
g.h.we=function(){return this.g?k7(this.g).we:!1};
g.h.hasNext=function(){return this.g?k7(this.g).hasNext:!1};
g.h.ed=function(a,b){this.D=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=k7(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.W(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Zb():!a.isAdPlaying()&&this.player.Zb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+c7(a):a.l,isPeggedToLive:1>=(a.u?a.i+c7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+c7(a):a.i,seekableStart:0<a.o?a.o+
c7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Am=function(){this.g&&this.g.Am()};
g.h.IG=function(a){1==a&&(this.C=this.g?k7(this.g):null)};
g.h.eJ=function(){var a=U7()?new j7(P7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Xf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,e7(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Rx=function(){this.A=[this.i].concat(gpa());var a=Q7()||this.i;k8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.cJ=function(){var a=Q7();k8(this,a)};
g.h.bJ=function(){this.l=Q7()};
g.h.Wb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Z6():k8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&Z6(),!0):!1}};
g.h.Or=function(){this.g.Or()};
g.h.Kb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.vU.remote=j8;})(_yt_player);
