# Generated by Django 2.0.9 on 2018-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
