# Generated by Django 2.0.9 on 2018-10-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_like_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='test',
        ),
    ]
